/*
Seagate Management Controller (MC) OpenAPI

This API allows users to interact through the MC API to provision and manage storage.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the PowerSuppliesResourceInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PowerSuppliesResourceInner{}

// PowerSuppliesResourceInner struct for PowerSuppliesResourceInner
type PowerSuppliesResourceInner struct {
	ObjectName                *string `json:"object-name,omitempty"`
	Meta                      *string `json:"meta,omitempty"`
	ConfigurationSerialnumber *string `json:"configuration-serialnumber,omitempty"`
	DashLevel                 *string `json:"dash-level,omitempty"`
	Dc12i                     *int64  `json:"dc12i,omitempty"`
	Dc12v                     *int64  `json:"dc12v,omitempty"`
	Dc33v                     *int64  `json:"dc33v,omitempty"`
	Dc5i                      *int64  `json:"dc5i,omitempty"`
	Dc5v                      *int64  `json:"dc5v,omitempty"`
	Dctemp                    *int64  `json:"dctemp,omitempty"`
	Description               *string `json:"description,omitempty"`
	DomId                     *int64  `json:"dom-id,omitempty"`
	DurableId                 *string `json:"durable-id,omitempty"`
	EnclosureId               *int64  `json:"enclosure-id,omitempty"`
	EnclosuresUrl             *string `json:"enclosures-url,omitempty"`
	FruShortname              *string `json:"fru-shortname,omitempty"`
	// Firmware version of the FRU
	FwRevision           *string `json:"fw-revision,omitempty"`
	Health               *string `json:"health,omitempty"`
	HealthNumeric        *int64  `json:"health-numeric,omitempty"`
	HealthReason         *string `json:"health-reason,omitempty"`
	HealthRecommendation *string `json:"health-recommendation,omitempty"`
	Location             *string `json:"location,omitempty"`
	MfgDate              *string `json:"mfg-date,omitempty"`
	MfgDateNumeric       *int64  `json:"mfg-date-numeric,omitempty"`
	MfgLocation          *string `json:"mfg-location,omitempty"`
	MfgVendorId          *string `json:"mfg-vendor-id,omitempty"`
	Model                *string `json:"model,omitempty"`
	Name                 *string `json:"name,omitempty"`
	PartNumber           *string `json:"part-number,omitempty"`
	// Position of the component in the enclosure
	Position *string `json:"position,omitempty"`
	// Position of the component in the enclosure( In numeric form )
	PositionNumeric *int64 `json:"position-numeric,omitempty"`
	// Current revision for this FRU
	Revision      *string `json:"revision,omitempty"`
	SerialNumber  *string `json:"serial-number,omitempty"`
	Status        *string `json:"status,omitempty"`
	StatusNumeric *int64  `json:"status-numeric,omitempty"`
	// The resource URL
	Url    *string            `json:"url,omitempty"`
	Vendor *string            `json:"vendor,omitempty"`
	Fan    []FanResourceInner `json:"fan,omitempty"`
}

// NewPowerSuppliesResourceInner instantiates a new PowerSuppliesResourceInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPowerSuppliesResourceInner() *PowerSuppliesResourceInner {
	this := PowerSuppliesResourceInner{}
	return &this
}

// NewPowerSuppliesResourceInnerWithDefaults instantiates a new PowerSuppliesResourceInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPowerSuppliesResourceInnerWithDefaults() *PowerSuppliesResourceInner {
	this := PowerSuppliesResourceInner{}
	return &this
}

// GetObjectName returns the ObjectName field value if set, zero value otherwise.
func (o *PowerSuppliesResourceInner) GetObjectName() string {
	if o == nil || IsNil(o.ObjectName) {
		var ret string
		return ret
	}
	return *o.ObjectName
}

// GetObjectNameOk returns a tuple with the ObjectName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PowerSuppliesResourceInner) GetObjectNameOk() (*string, bool) {
	if o == nil || IsNil(o.ObjectName) {
		return nil, false
	}
	return o.ObjectName, true
}

// HasObjectName returns a boolean if a field has been set.
func (o *PowerSuppliesResourceInner) HasObjectName() bool {
	if o != nil && !IsNil(o.ObjectName) {
		return true
	}

	return false
}

// SetObjectName gets a reference to the given string and assigns it to the ObjectName field.
func (o *PowerSuppliesResourceInner) SetObjectName(v string) {
	o.ObjectName = &v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *PowerSuppliesResourceInner) GetMeta() string {
	if o == nil || IsNil(o.Meta) {
		var ret string
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PowerSuppliesResourceInner) GetMetaOk() (*string, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *PowerSuppliesResourceInner) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given string and assigns it to the Meta field.
func (o *PowerSuppliesResourceInner) SetMeta(v string) {
	o.Meta = &v
}

// GetConfigurationSerialnumber returns the ConfigurationSerialnumber field value if set, zero value otherwise.
func (o *PowerSuppliesResourceInner) GetConfigurationSerialnumber() string {
	if o == nil || IsNil(o.ConfigurationSerialnumber) {
		var ret string
		return ret
	}
	return *o.ConfigurationSerialnumber
}

// GetConfigurationSerialnumberOk returns a tuple with the ConfigurationSerialnumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PowerSuppliesResourceInner) GetConfigurationSerialnumberOk() (*string, bool) {
	if o == nil || IsNil(o.ConfigurationSerialnumber) {
		return nil, false
	}
	return o.ConfigurationSerialnumber, true
}

// HasConfigurationSerialnumber returns a boolean if a field has been set.
func (o *PowerSuppliesResourceInner) HasConfigurationSerialnumber() bool {
	if o != nil && !IsNil(o.ConfigurationSerialnumber) {
		return true
	}

	return false
}

// SetConfigurationSerialnumber gets a reference to the given string and assigns it to the ConfigurationSerialnumber field.
func (o *PowerSuppliesResourceInner) SetConfigurationSerialnumber(v string) {
	o.ConfigurationSerialnumber = &v
}

// GetDashLevel returns the DashLevel field value if set, zero value otherwise.
func (o *PowerSuppliesResourceInner) GetDashLevel() string {
	if o == nil || IsNil(o.DashLevel) {
		var ret string
		return ret
	}
	return *o.DashLevel
}

// GetDashLevelOk returns a tuple with the DashLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PowerSuppliesResourceInner) GetDashLevelOk() (*string, bool) {
	if o == nil || IsNil(o.DashLevel) {
		return nil, false
	}
	return o.DashLevel, true
}

// HasDashLevel returns a boolean if a field has been set.
func (o *PowerSuppliesResourceInner) HasDashLevel() bool {
	if o != nil && !IsNil(o.DashLevel) {
		return true
	}

	return false
}

// SetDashLevel gets a reference to the given string and assigns it to the DashLevel field.
func (o *PowerSuppliesResourceInner) SetDashLevel(v string) {
	o.DashLevel = &v
}

// GetDc12i returns the Dc12i field value if set, zero value otherwise.
func (o *PowerSuppliesResourceInner) GetDc12i() int64 {
	if o == nil || IsNil(o.Dc12i) {
		var ret int64
		return ret
	}
	return *o.Dc12i
}

// GetDc12iOk returns a tuple with the Dc12i field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PowerSuppliesResourceInner) GetDc12iOk() (*int64, bool) {
	if o == nil || IsNil(o.Dc12i) {
		return nil, false
	}
	return o.Dc12i, true
}

// HasDc12i returns a boolean if a field has been set.
func (o *PowerSuppliesResourceInner) HasDc12i() bool {
	if o != nil && !IsNil(o.Dc12i) {
		return true
	}

	return false
}

// SetDc12i gets a reference to the given int64 and assigns it to the Dc12i field.
func (o *PowerSuppliesResourceInner) SetDc12i(v int64) {
	o.Dc12i = &v
}

// GetDc12v returns the Dc12v field value if set, zero value otherwise.
func (o *PowerSuppliesResourceInner) GetDc12v() int64 {
	if o == nil || IsNil(o.Dc12v) {
		var ret int64
		return ret
	}
	return *o.Dc12v
}

// GetDc12vOk returns a tuple with the Dc12v field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PowerSuppliesResourceInner) GetDc12vOk() (*int64, bool) {
	if o == nil || IsNil(o.Dc12v) {
		return nil, false
	}
	return o.Dc12v, true
}

// HasDc12v returns a boolean if a field has been set.
func (o *PowerSuppliesResourceInner) HasDc12v() bool {
	if o != nil && !IsNil(o.Dc12v) {
		return true
	}

	return false
}

// SetDc12v gets a reference to the given int64 and assigns it to the Dc12v field.
func (o *PowerSuppliesResourceInner) SetDc12v(v int64) {
	o.Dc12v = &v
}

// GetDc33v returns the Dc33v field value if set, zero value otherwise.
func (o *PowerSuppliesResourceInner) GetDc33v() int64 {
	if o == nil || IsNil(o.Dc33v) {
		var ret int64
		return ret
	}
	return *o.Dc33v
}

// GetDc33vOk returns a tuple with the Dc33v field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PowerSuppliesResourceInner) GetDc33vOk() (*int64, bool) {
	if o == nil || IsNil(o.Dc33v) {
		return nil, false
	}
	return o.Dc33v, true
}

// HasDc33v returns a boolean if a field has been set.
func (o *PowerSuppliesResourceInner) HasDc33v() bool {
	if o != nil && !IsNil(o.Dc33v) {
		return true
	}

	return false
}

// SetDc33v gets a reference to the given int64 and assigns it to the Dc33v field.
func (o *PowerSuppliesResourceInner) SetDc33v(v int64) {
	o.Dc33v = &v
}

// GetDc5i returns the Dc5i field value if set, zero value otherwise.
func (o *PowerSuppliesResourceInner) GetDc5i() int64 {
	if o == nil || IsNil(o.Dc5i) {
		var ret int64
		return ret
	}
	return *o.Dc5i
}

// GetDc5iOk returns a tuple with the Dc5i field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PowerSuppliesResourceInner) GetDc5iOk() (*int64, bool) {
	if o == nil || IsNil(o.Dc5i) {
		return nil, false
	}
	return o.Dc5i, true
}

// HasDc5i returns a boolean if a field has been set.
func (o *PowerSuppliesResourceInner) HasDc5i() bool {
	if o != nil && !IsNil(o.Dc5i) {
		return true
	}

	return false
}

// SetDc5i gets a reference to the given int64 and assigns it to the Dc5i field.
func (o *PowerSuppliesResourceInner) SetDc5i(v int64) {
	o.Dc5i = &v
}

// GetDc5v returns the Dc5v field value if set, zero value otherwise.
func (o *PowerSuppliesResourceInner) GetDc5v() int64 {
	if o == nil || IsNil(o.Dc5v) {
		var ret int64
		return ret
	}
	return *o.Dc5v
}

// GetDc5vOk returns a tuple with the Dc5v field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PowerSuppliesResourceInner) GetDc5vOk() (*int64, bool) {
	if o == nil || IsNil(o.Dc5v) {
		return nil, false
	}
	return o.Dc5v, true
}

// HasDc5v returns a boolean if a field has been set.
func (o *PowerSuppliesResourceInner) HasDc5v() bool {
	if o != nil && !IsNil(o.Dc5v) {
		return true
	}

	return false
}

// SetDc5v gets a reference to the given int64 and assigns it to the Dc5v field.
func (o *PowerSuppliesResourceInner) SetDc5v(v int64) {
	o.Dc5v = &v
}

// GetDctemp returns the Dctemp field value if set, zero value otherwise.
func (o *PowerSuppliesResourceInner) GetDctemp() int64 {
	if o == nil || IsNil(o.Dctemp) {
		var ret int64
		return ret
	}
	return *o.Dctemp
}

// GetDctempOk returns a tuple with the Dctemp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PowerSuppliesResourceInner) GetDctempOk() (*int64, bool) {
	if o == nil || IsNil(o.Dctemp) {
		return nil, false
	}
	return o.Dctemp, true
}

// HasDctemp returns a boolean if a field has been set.
func (o *PowerSuppliesResourceInner) HasDctemp() bool {
	if o != nil && !IsNil(o.Dctemp) {
		return true
	}

	return false
}

// SetDctemp gets a reference to the given int64 and assigns it to the Dctemp field.
func (o *PowerSuppliesResourceInner) SetDctemp(v int64) {
	o.Dctemp = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *PowerSuppliesResourceInner) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PowerSuppliesResourceInner) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *PowerSuppliesResourceInner) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *PowerSuppliesResourceInner) SetDescription(v string) {
	o.Description = &v
}

// GetDomId returns the DomId field value if set, zero value otherwise.
func (o *PowerSuppliesResourceInner) GetDomId() int64 {
	if o == nil || IsNil(o.DomId) {
		var ret int64
		return ret
	}
	return *o.DomId
}

// GetDomIdOk returns a tuple with the DomId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PowerSuppliesResourceInner) GetDomIdOk() (*int64, bool) {
	if o == nil || IsNil(o.DomId) {
		return nil, false
	}
	return o.DomId, true
}

// HasDomId returns a boolean if a field has been set.
func (o *PowerSuppliesResourceInner) HasDomId() bool {
	if o != nil && !IsNil(o.DomId) {
		return true
	}

	return false
}

// SetDomId gets a reference to the given int64 and assigns it to the DomId field.
func (o *PowerSuppliesResourceInner) SetDomId(v int64) {
	o.DomId = &v
}

// GetDurableId returns the DurableId field value if set, zero value otherwise.
func (o *PowerSuppliesResourceInner) GetDurableId() string {
	if o == nil || IsNil(o.DurableId) {
		var ret string
		return ret
	}
	return *o.DurableId
}

// GetDurableIdOk returns a tuple with the DurableId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PowerSuppliesResourceInner) GetDurableIdOk() (*string, bool) {
	if o == nil || IsNil(o.DurableId) {
		return nil, false
	}
	return o.DurableId, true
}

// HasDurableId returns a boolean if a field has been set.
func (o *PowerSuppliesResourceInner) HasDurableId() bool {
	if o != nil && !IsNil(o.DurableId) {
		return true
	}

	return false
}

// SetDurableId gets a reference to the given string and assigns it to the DurableId field.
func (o *PowerSuppliesResourceInner) SetDurableId(v string) {
	o.DurableId = &v
}

// GetEnclosureId returns the EnclosureId field value if set, zero value otherwise.
func (o *PowerSuppliesResourceInner) GetEnclosureId() int64 {
	if o == nil || IsNil(o.EnclosureId) {
		var ret int64
		return ret
	}
	return *o.EnclosureId
}

// GetEnclosureIdOk returns a tuple with the EnclosureId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PowerSuppliesResourceInner) GetEnclosureIdOk() (*int64, bool) {
	if o == nil || IsNil(o.EnclosureId) {
		return nil, false
	}
	return o.EnclosureId, true
}

// HasEnclosureId returns a boolean if a field has been set.
func (o *PowerSuppliesResourceInner) HasEnclosureId() bool {
	if o != nil && !IsNil(o.EnclosureId) {
		return true
	}

	return false
}

// SetEnclosureId gets a reference to the given int64 and assigns it to the EnclosureId field.
func (o *PowerSuppliesResourceInner) SetEnclosureId(v int64) {
	o.EnclosureId = &v
}

// GetEnclosuresUrl returns the EnclosuresUrl field value if set, zero value otherwise.
func (o *PowerSuppliesResourceInner) GetEnclosuresUrl() string {
	if o == nil || IsNil(o.EnclosuresUrl) {
		var ret string
		return ret
	}
	return *o.EnclosuresUrl
}

// GetEnclosuresUrlOk returns a tuple with the EnclosuresUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PowerSuppliesResourceInner) GetEnclosuresUrlOk() (*string, bool) {
	if o == nil || IsNil(o.EnclosuresUrl) {
		return nil, false
	}
	return o.EnclosuresUrl, true
}

// HasEnclosuresUrl returns a boolean if a field has been set.
func (o *PowerSuppliesResourceInner) HasEnclosuresUrl() bool {
	if o != nil && !IsNil(o.EnclosuresUrl) {
		return true
	}

	return false
}

// SetEnclosuresUrl gets a reference to the given string and assigns it to the EnclosuresUrl field.
func (o *PowerSuppliesResourceInner) SetEnclosuresUrl(v string) {
	o.EnclosuresUrl = &v
}

// GetFruShortname returns the FruShortname field value if set, zero value otherwise.
func (o *PowerSuppliesResourceInner) GetFruShortname() string {
	if o == nil || IsNil(o.FruShortname) {
		var ret string
		return ret
	}
	return *o.FruShortname
}

// GetFruShortnameOk returns a tuple with the FruShortname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PowerSuppliesResourceInner) GetFruShortnameOk() (*string, bool) {
	if o == nil || IsNil(o.FruShortname) {
		return nil, false
	}
	return o.FruShortname, true
}

// HasFruShortname returns a boolean if a field has been set.
func (o *PowerSuppliesResourceInner) HasFruShortname() bool {
	if o != nil && !IsNil(o.FruShortname) {
		return true
	}

	return false
}

// SetFruShortname gets a reference to the given string and assigns it to the FruShortname field.
func (o *PowerSuppliesResourceInner) SetFruShortname(v string) {
	o.FruShortname = &v
}

// GetFwRevision returns the FwRevision field value if set, zero value otherwise.
func (o *PowerSuppliesResourceInner) GetFwRevision() string {
	if o == nil || IsNil(o.FwRevision) {
		var ret string
		return ret
	}
	return *o.FwRevision
}

// GetFwRevisionOk returns a tuple with the FwRevision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PowerSuppliesResourceInner) GetFwRevisionOk() (*string, bool) {
	if o == nil || IsNil(o.FwRevision) {
		return nil, false
	}
	return o.FwRevision, true
}

// HasFwRevision returns a boolean if a field has been set.
func (o *PowerSuppliesResourceInner) HasFwRevision() bool {
	if o != nil && !IsNil(o.FwRevision) {
		return true
	}

	return false
}

// SetFwRevision gets a reference to the given string and assigns it to the FwRevision field.
func (o *PowerSuppliesResourceInner) SetFwRevision(v string) {
	o.FwRevision = &v
}

// GetHealth returns the Health field value if set, zero value otherwise.
func (o *PowerSuppliesResourceInner) GetHealth() string {
	if o == nil || IsNil(o.Health) {
		var ret string
		return ret
	}
	return *o.Health
}

// GetHealthOk returns a tuple with the Health field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PowerSuppliesResourceInner) GetHealthOk() (*string, bool) {
	if o == nil || IsNil(o.Health) {
		return nil, false
	}
	return o.Health, true
}

// HasHealth returns a boolean if a field has been set.
func (o *PowerSuppliesResourceInner) HasHealth() bool {
	if o != nil && !IsNil(o.Health) {
		return true
	}

	return false
}

// SetHealth gets a reference to the given string and assigns it to the Health field.
func (o *PowerSuppliesResourceInner) SetHealth(v string) {
	o.Health = &v
}

// GetHealthNumeric returns the HealthNumeric field value if set, zero value otherwise.
func (o *PowerSuppliesResourceInner) GetHealthNumeric() int64 {
	if o == nil || IsNil(o.HealthNumeric) {
		var ret int64
		return ret
	}
	return *o.HealthNumeric
}

// GetHealthNumericOk returns a tuple with the HealthNumeric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PowerSuppliesResourceInner) GetHealthNumericOk() (*int64, bool) {
	if o == nil || IsNil(o.HealthNumeric) {
		return nil, false
	}
	return o.HealthNumeric, true
}

// HasHealthNumeric returns a boolean if a field has been set.
func (o *PowerSuppliesResourceInner) HasHealthNumeric() bool {
	if o != nil && !IsNil(o.HealthNumeric) {
		return true
	}

	return false
}

// SetHealthNumeric gets a reference to the given int64 and assigns it to the HealthNumeric field.
func (o *PowerSuppliesResourceInner) SetHealthNumeric(v int64) {
	o.HealthNumeric = &v
}

// GetHealthReason returns the HealthReason field value if set, zero value otherwise.
func (o *PowerSuppliesResourceInner) GetHealthReason() string {
	if o == nil || IsNil(o.HealthReason) {
		var ret string
		return ret
	}
	return *o.HealthReason
}

// GetHealthReasonOk returns a tuple with the HealthReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PowerSuppliesResourceInner) GetHealthReasonOk() (*string, bool) {
	if o == nil || IsNil(o.HealthReason) {
		return nil, false
	}
	return o.HealthReason, true
}

// HasHealthReason returns a boolean if a field has been set.
func (o *PowerSuppliesResourceInner) HasHealthReason() bool {
	if o != nil && !IsNil(o.HealthReason) {
		return true
	}

	return false
}

// SetHealthReason gets a reference to the given string and assigns it to the HealthReason field.
func (o *PowerSuppliesResourceInner) SetHealthReason(v string) {
	o.HealthReason = &v
}

// GetHealthRecommendation returns the HealthRecommendation field value if set, zero value otherwise.
func (o *PowerSuppliesResourceInner) GetHealthRecommendation() string {
	if o == nil || IsNil(o.HealthRecommendation) {
		var ret string
		return ret
	}
	return *o.HealthRecommendation
}

// GetHealthRecommendationOk returns a tuple with the HealthRecommendation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PowerSuppliesResourceInner) GetHealthRecommendationOk() (*string, bool) {
	if o == nil || IsNil(o.HealthRecommendation) {
		return nil, false
	}
	return o.HealthRecommendation, true
}

// HasHealthRecommendation returns a boolean if a field has been set.
func (o *PowerSuppliesResourceInner) HasHealthRecommendation() bool {
	if o != nil && !IsNil(o.HealthRecommendation) {
		return true
	}

	return false
}

// SetHealthRecommendation gets a reference to the given string and assigns it to the HealthRecommendation field.
func (o *PowerSuppliesResourceInner) SetHealthRecommendation(v string) {
	o.HealthRecommendation = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *PowerSuppliesResourceInner) GetLocation() string {
	if o == nil || IsNil(o.Location) {
		var ret string
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PowerSuppliesResourceInner) GetLocationOk() (*string, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *PowerSuppliesResourceInner) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given string and assigns it to the Location field.
func (o *PowerSuppliesResourceInner) SetLocation(v string) {
	o.Location = &v
}

// GetMfgDate returns the MfgDate field value if set, zero value otherwise.
func (o *PowerSuppliesResourceInner) GetMfgDate() string {
	if o == nil || IsNil(o.MfgDate) {
		var ret string
		return ret
	}
	return *o.MfgDate
}

// GetMfgDateOk returns a tuple with the MfgDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PowerSuppliesResourceInner) GetMfgDateOk() (*string, bool) {
	if o == nil || IsNil(o.MfgDate) {
		return nil, false
	}
	return o.MfgDate, true
}

// HasMfgDate returns a boolean if a field has been set.
func (o *PowerSuppliesResourceInner) HasMfgDate() bool {
	if o != nil && !IsNil(o.MfgDate) {
		return true
	}

	return false
}

// SetMfgDate gets a reference to the given string and assigns it to the MfgDate field.
func (o *PowerSuppliesResourceInner) SetMfgDate(v string) {
	o.MfgDate = &v
}

// GetMfgDateNumeric returns the MfgDateNumeric field value if set, zero value otherwise.
func (o *PowerSuppliesResourceInner) GetMfgDateNumeric() int64 {
	if o == nil || IsNil(o.MfgDateNumeric) {
		var ret int64
		return ret
	}
	return *o.MfgDateNumeric
}

// GetMfgDateNumericOk returns a tuple with the MfgDateNumeric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PowerSuppliesResourceInner) GetMfgDateNumericOk() (*int64, bool) {
	if o == nil || IsNil(o.MfgDateNumeric) {
		return nil, false
	}
	return o.MfgDateNumeric, true
}

// HasMfgDateNumeric returns a boolean if a field has been set.
func (o *PowerSuppliesResourceInner) HasMfgDateNumeric() bool {
	if o != nil && !IsNil(o.MfgDateNumeric) {
		return true
	}

	return false
}

// SetMfgDateNumeric gets a reference to the given int64 and assigns it to the MfgDateNumeric field.
func (o *PowerSuppliesResourceInner) SetMfgDateNumeric(v int64) {
	o.MfgDateNumeric = &v
}

// GetMfgLocation returns the MfgLocation field value if set, zero value otherwise.
func (o *PowerSuppliesResourceInner) GetMfgLocation() string {
	if o == nil || IsNil(o.MfgLocation) {
		var ret string
		return ret
	}
	return *o.MfgLocation
}

// GetMfgLocationOk returns a tuple with the MfgLocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PowerSuppliesResourceInner) GetMfgLocationOk() (*string, bool) {
	if o == nil || IsNil(o.MfgLocation) {
		return nil, false
	}
	return o.MfgLocation, true
}

// HasMfgLocation returns a boolean if a field has been set.
func (o *PowerSuppliesResourceInner) HasMfgLocation() bool {
	if o != nil && !IsNil(o.MfgLocation) {
		return true
	}

	return false
}

// SetMfgLocation gets a reference to the given string and assigns it to the MfgLocation field.
func (o *PowerSuppliesResourceInner) SetMfgLocation(v string) {
	o.MfgLocation = &v
}

// GetMfgVendorId returns the MfgVendorId field value if set, zero value otherwise.
func (o *PowerSuppliesResourceInner) GetMfgVendorId() string {
	if o == nil || IsNil(o.MfgVendorId) {
		var ret string
		return ret
	}
	return *o.MfgVendorId
}

// GetMfgVendorIdOk returns a tuple with the MfgVendorId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PowerSuppliesResourceInner) GetMfgVendorIdOk() (*string, bool) {
	if o == nil || IsNil(o.MfgVendorId) {
		return nil, false
	}
	return o.MfgVendorId, true
}

// HasMfgVendorId returns a boolean if a field has been set.
func (o *PowerSuppliesResourceInner) HasMfgVendorId() bool {
	if o != nil && !IsNil(o.MfgVendorId) {
		return true
	}

	return false
}

// SetMfgVendorId gets a reference to the given string and assigns it to the MfgVendorId field.
func (o *PowerSuppliesResourceInner) SetMfgVendorId(v string) {
	o.MfgVendorId = &v
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *PowerSuppliesResourceInner) GetModel() string {
	if o == nil || IsNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PowerSuppliesResourceInner) GetModelOk() (*string, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *PowerSuppliesResourceInner) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *PowerSuppliesResourceInner) SetModel(v string) {
	o.Model = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PowerSuppliesResourceInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PowerSuppliesResourceInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PowerSuppliesResourceInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PowerSuppliesResourceInner) SetName(v string) {
	o.Name = &v
}

// GetPartNumber returns the PartNumber field value if set, zero value otherwise.
func (o *PowerSuppliesResourceInner) GetPartNumber() string {
	if o == nil || IsNil(o.PartNumber) {
		var ret string
		return ret
	}
	return *o.PartNumber
}

// GetPartNumberOk returns a tuple with the PartNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PowerSuppliesResourceInner) GetPartNumberOk() (*string, bool) {
	if o == nil || IsNil(o.PartNumber) {
		return nil, false
	}
	return o.PartNumber, true
}

// HasPartNumber returns a boolean if a field has been set.
func (o *PowerSuppliesResourceInner) HasPartNumber() bool {
	if o != nil && !IsNil(o.PartNumber) {
		return true
	}

	return false
}

// SetPartNumber gets a reference to the given string and assigns it to the PartNumber field.
func (o *PowerSuppliesResourceInner) SetPartNumber(v string) {
	o.PartNumber = &v
}

// GetPosition returns the Position field value if set, zero value otherwise.
func (o *PowerSuppliesResourceInner) GetPosition() string {
	if o == nil || IsNil(o.Position) {
		var ret string
		return ret
	}
	return *o.Position
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PowerSuppliesResourceInner) GetPositionOk() (*string, bool) {
	if o == nil || IsNil(o.Position) {
		return nil, false
	}
	return o.Position, true
}

// HasPosition returns a boolean if a field has been set.
func (o *PowerSuppliesResourceInner) HasPosition() bool {
	if o != nil && !IsNil(o.Position) {
		return true
	}

	return false
}

// SetPosition gets a reference to the given string and assigns it to the Position field.
func (o *PowerSuppliesResourceInner) SetPosition(v string) {
	o.Position = &v
}

// GetPositionNumeric returns the PositionNumeric field value if set, zero value otherwise.
func (o *PowerSuppliesResourceInner) GetPositionNumeric() int64 {
	if o == nil || IsNil(o.PositionNumeric) {
		var ret int64
		return ret
	}
	return *o.PositionNumeric
}

// GetPositionNumericOk returns a tuple with the PositionNumeric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PowerSuppliesResourceInner) GetPositionNumericOk() (*int64, bool) {
	if o == nil || IsNil(o.PositionNumeric) {
		return nil, false
	}
	return o.PositionNumeric, true
}

// HasPositionNumeric returns a boolean if a field has been set.
func (o *PowerSuppliesResourceInner) HasPositionNumeric() bool {
	if o != nil && !IsNil(o.PositionNumeric) {
		return true
	}

	return false
}

// SetPositionNumeric gets a reference to the given int64 and assigns it to the PositionNumeric field.
func (o *PowerSuppliesResourceInner) SetPositionNumeric(v int64) {
	o.PositionNumeric = &v
}

// GetRevision returns the Revision field value if set, zero value otherwise.
func (o *PowerSuppliesResourceInner) GetRevision() string {
	if o == nil || IsNil(o.Revision) {
		var ret string
		return ret
	}
	return *o.Revision
}

// GetRevisionOk returns a tuple with the Revision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PowerSuppliesResourceInner) GetRevisionOk() (*string, bool) {
	if o == nil || IsNil(o.Revision) {
		return nil, false
	}
	return o.Revision, true
}

// HasRevision returns a boolean if a field has been set.
func (o *PowerSuppliesResourceInner) HasRevision() bool {
	if o != nil && !IsNil(o.Revision) {
		return true
	}

	return false
}

// SetRevision gets a reference to the given string and assigns it to the Revision field.
func (o *PowerSuppliesResourceInner) SetRevision(v string) {
	o.Revision = &v
}

// GetSerialNumber returns the SerialNumber field value if set, zero value otherwise.
func (o *PowerSuppliesResourceInner) GetSerialNumber() string {
	if o == nil || IsNil(o.SerialNumber) {
		var ret string
		return ret
	}
	return *o.SerialNumber
}

// GetSerialNumberOk returns a tuple with the SerialNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PowerSuppliesResourceInner) GetSerialNumberOk() (*string, bool) {
	if o == nil || IsNil(o.SerialNumber) {
		return nil, false
	}
	return o.SerialNumber, true
}

// HasSerialNumber returns a boolean if a field has been set.
func (o *PowerSuppliesResourceInner) HasSerialNumber() bool {
	if o != nil && !IsNil(o.SerialNumber) {
		return true
	}

	return false
}

// SetSerialNumber gets a reference to the given string and assigns it to the SerialNumber field.
func (o *PowerSuppliesResourceInner) SetSerialNumber(v string) {
	o.SerialNumber = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *PowerSuppliesResourceInner) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PowerSuppliesResourceInner) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *PowerSuppliesResourceInner) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *PowerSuppliesResourceInner) SetStatus(v string) {
	o.Status = &v
}

// GetStatusNumeric returns the StatusNumeric field value if set, zero value otherwise.
func (o *PowerSuppliesResourceInner) GetStatusNumeric() int64 {
	if o == nil || IsNil(o.StatusNumeric) {
		var ret int64
		return ret
	}
	return *o.StatusNumeric
}

// GetStatusNumericOk returns a tuple with the StatusNumeric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PowerSuppliesResourceInner) GetStatusNumericOk() (*int64, bool) {
	if o == nil || IsNil(o.StatusNumeric) {
		return nil, false
	}
	return o.StatusNumeric, true
}

// HasStatusNumeric returns a boolean if a field has been set.
func (o *PowerSuppliesResourceInner) HasStatusNumeric() bool {
	if o != nil && !IsNil(o.StatusNumeric) {
		return true
	}

	return false
}

// SetStatusNumeric gets a reference to the given int64 and assigns it to the StatusNumeric field.
func (o *PowerSuppliesResourceInner) SetStatusNumeric(v int64) {
	o.StatusNumeric = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *PowerSuppliesResourceInner) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PowerSuppliesResourceInner) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *PowerSuppliesResourceInner) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *PowerSuppliesResourceInner) SetUrl(v string) {
	o.Url = &v
}

// GetVendor returns the Vendor field value if set, zero value otherwise.
func (o *PowerSuppliesResourceInner) GetVendor() string {
	if o == nil || IsNil(o.Vendor) {
		var ret string
		return ret
	}
	return *o.Vendor
}

// GetVendorOk returns a tuple with the Vendor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PowerSuppliesResourceInner) GetVendorOk() (*string, bool) {
	if o == nil || IsNil(o.Vendor) {
		return nil, false
	}
	return o.Vendor, true
}

// HasVendor returns a boolean if a field has been set.
func (o *PowerSuppliesResourceInner) HasVendor() bool {
	if o != nil && !IsNil(o.Vendor) {
		return true
	}

	return false
}

// SetVendor gets a reference to the given string and assigns it to the Vendor field.
func (o *PowerSuppliesResourceInner) SetVendor(v string) {
	o.Vendor = &v
}

// GetFan returns the Fan field value if set, zero value otherwise.
func (o *PowerSuppliesResourceInner) GetFan() []FanResourceInner {
	if o == nil || IsNil(o.Fan) {
		var ret []FanResourceInner
		return ret
	}
	return o.Fan
}

// GetFanOk returns a tuple with the Fan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PowerSuppliesResourceInner) GetFanOk() ([]FanResourceInner, bool) {
	if o == nil || IsNil(o.Fan) {
		return nil, false
	}
	return o.Fan, true
}

// HasFan returns a boolean if a field has been set.
func (o *PowerSuppliesResourceInner) HasFan() bool {
	if o != nil && !IsNil(o.Fan) {
		return true
	}

	return false
}

// SetFan gets a reference to the given []FanResourceInner and assigns it to the Fan field.
func (o *PowerSuppliesResourceInner) SetFan(v []FanResourceInner) {
	o.Fan = v
}

func (o PowerSuppliesResourceInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PowerSuppliesResourceInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ObjectName) {
		toSerialize["object-name"] = o.ObjectName
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	if !IsNil(o.ConfigurationSerialnumber) {
		toSerialize["configuration-serialnumber"] = o.ConfigurationSerialnumber
	}
	if !IsNil(o.DashLevel) {
		toSerialize["dash-level"] = o.DashLevel
	}
	if !IsNil(o.Dc12i) {
		toSerialize["dc12i"] = o.Dc12i
	}
	if !IsNil(o.Dc12v) {
		toSerialize["dc12v"] = o.Dc12v
	}
	if !IsNil(o.Dc33v) {
		toSerialize["dc33v"] = o.Dc33v
	}
	if !IsNil(o.Dc5i) {
		toSerialize["dc5i"] = o.Dc5i
	}
	if !IsNil(o.Dc5v) {
		toSerialize["dc5v"] = o.Dc5v
	}
	if !IsNil(o.Dctemp) {
		toSerialize["dctemp"] = o.Dctemp
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.DomId) {
		toSerialize["dom-id"] = o.DomId
	}
	if !IsNil(o.DurableId) {
		toSerialize["durable-id"] = o.DurableId
	}
	if !IsNil(o.EnclosureId) {
		toSerialize["enclosure-id"] = o.EnclosureId
	}
	if !IsNil(o.EnclosuresUrl) {
		toSerialize["enclosures-url"] = o.EnclosuresUrl
	}
	if !IsNil(o.FruShortname) {
		toSerialize["fru-shortname"] = o.FruShortname
	}
	if !IsNil(o.FwRevision) {
		toSerialize["fw-revision"] = o.FwRevision
	}
	if !IsNil(o.Health) {
		toSerialize["health"] = o.Health
	}
	if !IsNil(o.HealthNumeric) {
		toSerialize["health-numeric"] = o.HealthNumeric
	}
	if !IsNil(o.HealthReason) {
		toSerialize["health-reason"] = o.HealthReason
	}
	if !IsNil(o.HealthRecommendation) {
		toSerialize["health-recommendation"] = o.HealthRecommendation
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if !IsNil(o.MfgDate) {
		toSerialize["mfg-date"] = o.MfgDate
	}
	if !IsNil(o.MfgDateNumeric) {
		toSerialize["mfg-date-numeric"] = o.MfgDateNumeric
	}
	if !IsNil(o.MfgLocation) {
		toSerialize["mfg-location"] = o.MfgLocation
	}
	if !IsNil(o.MfgVendorId) {
		toSerialize["mfg-vendor-id"] = o.MfgVendorId
	}
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.PartNumber) {
		toSerialize["part-number"] = o.PartNumber
	}
	if !IsNil(o.Position) {
		toSerialize["position"] = o.Position
	}
	if !IsNil(o.PositionNumeric) {
		toSerialize["position-numeric"] = o.PositionNumeric
	}
	if !IsNil(o.Revision) {
		toSerialize["revision"] = o.Revision
	}
	if !IsNil(o.SerialNumber) {
		toSerialize["serial-number"] = o.SerialNumber
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.StatusNumeric) {
		toSerialize["status-numeric"] = o.StatusNumeric
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Vendor) {
		toSerialize["vendor"] = o.Vendor
	}
	if !IsNil(o.Fan) {
		toSerialize["fan"] = o.Fan
	}
	return toSerialize, nil
}

type NullablePowerSuppliesResourceInner struct {
	value *PowerSuppliesResourceInner
	isSet bool
}

func (v NullablePowerSuppliesResourceInner) Get() *PowerSuppliesResourceInner {
	return v.value
}

func (v *NullablePowerSuppliesResourceInner) Set(val *PowerSuppliesResourceInner) {
	v.value = val
	v.isSet = true
}

func (v NullablePowerSuppliesResourceInner) IsSet() bool {
	return v.isSet
}

func (v *NullablePowerSuppliesResourceInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePowerSuppliesResourceInner(val *PowerSuppliesResourceInner) *NullablePowerSuppliesResourceInner {
	return &NullablePowerSuppliesResourceInner{value: val, isSet: true}
}

func (v NullablePowerSuppliesResourceInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePowerSuppliesResourceInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
