/*
Seagate Management Controller (MC) OpenAPI

This API allows users to interact through the MC API to provision and manage storage.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// PoolsResourceInner struct for PoolsResourceInner
type PoolsResourceInner struct {
	ObjectName *string `json:"object-name,omitempty"`
	Meta       *string `json:"meta,omitempty"`
	// Number of pages allocated
	AllocatedPages *int64 `json:"allocated-pages,omitempty"`
	// Available pages
	AvailablePages          *int64  `json:"available-pages,omitempty"`
	AvailableRfcSize        *string `json:"available-rfc-size,omitempty"`
	AvailableRfcSizeNumeric *int64  `json:"available-rfc-size-numeric,omitempty"`
	Blocksize               *int64  `json:"blocksize,omitempty"`
	CompressionEfficiency   *string `json:"compression-efficiency,omitempty"`
	DiskGroupsCount         *int64  `json:"disk-groups-count,omitempty"`
	// Extended status (bits)
	ExtendedStatus              *int64  `json:"extended-status,omitempty"`
	Health                      *string `json:"health,omitempty"`
	HealthNumeric               *int64  `json:"health-numeric,omitempty"`
	HealthReason                *string `json:"health-reason,omitempty"`
	HealthReasonNumeric         *int64  `json:"health-reason-numeric,omitempty"`
	HealthRecommendation        *string `json:"health-recommendation,omitempty"`
	HealthRecommendationNumeric *int64  `json:"health-recommendation-numeric,omitempty"`
	// High threshold percentage
	HighThreshold        *string `json:"high-threshold,omitempty"`
	IdlePageCheck        *string `json:"idle-page-check,omitempty"`
	IdlePageCheckNumeric *int64  `json:"idle-page-check-numeric,omitempty"`
	// Low threshold percentage
	LowThreshold *string `json:"low-threshold,omitempty"`
	// Pool Metadata currently in use
	MetadataAllocated *string `json:"metadata-allocated,omitempty"`
	// Pool Metadata currently in use( In numeric form )
	MetadataAllocatedNumeric *int64 `json:"metadata-allocated-numeric,omitempty"`
	// Pool Metadata available capacity
	MetadataAvailable *string `json:"metadata-available,omitempty"`
	// Pool Metadata available capacity( In numeric form )
	MetadataAvailableNumeric *int64 `json:"metadata-available-numeric,omitempty"`
	// Disk Group Metadata Total Size
	MetadataTotalSize *string `json:"metadata-total-size,omitempty"`
	// Disk Group Metadata Total Size( In numeric form )
	MetadataTotalSizeNumeric *int64 `json:"metadata-total-size-numeric,omitempty"`
	// Size of the storage pool metadata volume
	MetadataVolSize *string `json:"metadata-vol-size,omitempty"`
	// Size of the storage pool metadata volume( In numeric form )
	MetadataVolSizeNumeric *int64 `json:"metadata-vol-size-numeric,omitempty"`
	// Middle threshold percentage
	MiddleThreshold *string `json:"middle-threshold,omitempty"`
	// Migration between tiers
	Migration *string `json:"migration,omitempty"`
	// Migration between tiers( In numeric form )
	MigrationNumeric     *int64  `json:"migration-numeric,omitempty"`
	Name                 *string `json:"name,omitempty"`
	OverCommitted        *string `json:"over-committed,omitempty"`
	OverCommittedNumeric *int64  `json:"over-committed-numeric,omitempty"`
	Overcommit           *string `json:"overcommit,omitempty"`
	OvercommitNumeric    *int64  `json:"overcommit-numeric,omitempty"`
	// Controller owning the component
	Owner *string `json:"owner,omitempty"`
	// Controller owning the component( In numeric form )
	OwnerNumeric *int64 `json:"owner-numeric,omitempty"`
	// Page size in blocks
	PageSize *string `json:"page-size,omitempty"`
	// Page size in blocks( In numeric form )
	PageSizeNumeric *int64 `json:"page-size-numeric,omitempty"`
	// Pool Sector Format
	PoolSectorFormat *string `json:"pool-sector-format,omitempty"`
	// Pool Sector Format( In numeric form )
	PoolSectorFormatNumeric *int64 `json:"pool-sector-format-numeric,omitempty"`
	// Configured owner
	PreferredOwner *string `json:"preferred-owner,omitempty"`
	// Configured owner( In numeric form )
	PreferredOwnerNumeric *int64  `json:"preferred-owner-numeric,omitempty"`
	ReadFlashCache        *string `json:"read-flash-cache,omitempty"`
	ReadFlashCacheNumeric *int64  `json:"read-flash-cache-numeric,omitempty"`
	// Rebalance within the tier
	Rebalance *string `json:"rebalance,omitempty"`
	// Rebalance within the tier( In numeric form )
	RebalanceNumeric           *int64  `json:"rebalance-numeric,omitempty"`
	ReservedSize               *string `json:"reserved-size,omitempty"`
	ReservedSizeNumeric        *int64  `json:"reserved-size-numeric,omitempty"`
	ReservedUnallocSize        *string `json:"reserved-unalloc-size,omitempty"`
	ReservedUnallocSizeNumeric *int64  `json:"reserved-unalloc-size-numeric,omitempty"`
	SerialNumber               *string `json:"serial-number,omitempty"`
	SnapSize                   *string `json:"snap-size,omitempty"`
	SnapSizeNumeric            *int64  `json:"snap-size-numeric,omitempty"`
	// Storage type
	StorageType *string `json:"storage-type,omitempty"`
	// Storage type( In numeric form )
	StorageTypeNumeric  *int64  `json:"storage-type-numeric,omitempty"`
	TotalAvail          *string `json:"total-avail,omitempty"`
	TotalAvailNumeric   *int64  `json:"total-avail-numeric,omitempty"`
	TotalRfcSize        *string `json:"total-rfc-size,omitempty"`
	TotalRfcSizeNumeric *int64  `json:"total-rfc-size-numeric,omitempty"`
	// The total size formatted using the session settings for base, precision, and units
	TotalSize *string `json:"total-size,omitempty"`
	// The total size formatted using the session settings for base, precision, and units( In numeric form )
	TotalSizeNumeric *int64 `json:"total-size-numeric,omitempty"`
	// The resource URL
	Url                   *string `json:"url,omitempty"`
	UtilityRunning        *string `json:"utility-running,omitempty"`
	UtilityRunningNumeric *int64  `json:"utility-running-numeric,omitempty"`
	Volumes               *int64  `json:"volumes,omitempty"`
	// Scan for zero-value pages
	ZeroScan *string `json:"zero-scan,omitempty"`
	// Scan for zero-value pages( In numeric form )
	ZeroScanNumeric *int64                    `json:"zero-scan-numeric,omitempty"`
	DiskGroups      []DiskGroupsResourceInner `json:"disk-groups,omitempty"`
	Tiers           []TiersResourceInner      `json:"tiers,omitempty"`
}

// NewPoolsResourceInner instantiates a new PoolsResourceInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPoolsResourceInner() *PoolsResourceInner {
	this := PoolsResourceInner{}
	return &this
}

// NewPoolsResourceInnerWithDefaults instantiates a new PoolsResourceInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPoolsResourceInnerWithDefaults() *PoolsResourceInner {
	this := PoolsResourceInner{}
	return &this
}

// GetObjectName returns the ObjectName field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetObjectName() string {
	if o == nil || isNil(o.ObjectName) {
		var ret string
		return ret
	}
	return *o.ObjectName
}

// GetObjectNameOk returns a tuple with the ObjectName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetObjectNameOk() (*string, bool) {
	if o == nil || isNil(o.ObjectName) {
		return nil, false
	}
	return o.ObjectName, true
}

// HasObjectName returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasObjectName() bool {
	if o != nil && !isNil(o.ObjectName) {
		return true
	}

	return false
}

// SetObjectName gets a reference to the given string and assigns it to the ObjectName field.
func (o *PoolsResourceInner) SetObjectName(v string) {
	o.ObjectName = &v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetMeta() string {
	if o == nil || isNil(o.Meta) {
		var ret string
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetMetaOk() (*string, bool) {
	if o == nil || isNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasMeta() bool {
	if o != nil && !isNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given string and assigns it to the Meta field.
func (o *PoolsResourceInner) SetMeta(v string) {
	o.Meta = &v
}

// GetAllocatedPages returns the AllocatedPages field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetAllocatedPages() int64 {
	if o == nil || isNil(o.AllocatedPages) {
		var ret int64
		return ret
	}
	return *o.AllocatedPages
}

// GetAllocatedPagesOk returns a tuple with the AllocatedPages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetAllocatedPagesOk() (*int64, bool) {
	if o == nil || isNil(o.AllocatedPages) {
		return nil, false
	}
	return o.AllocatedPages, true
}

// HasAllocatedPages returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasAllocatedPages() bool {
	if o != nil && !isNil(o.AllocatedPages) {
		return true
	}

	return false
}

// SetAllocatedPages gets a reference to the given int64 and assigns it to the AllocatedPages field.
func (o *PoolsResourceInner) SetAllocatedPages(v int64) {
	o.AllocatedPages = &v
}

// GetAvailablePages returns the AvailablePages field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetAvailablePages() int64 {
	if o == nil || isNil(o.AvailablePages) {
		var ret int64
		return ret
	}
	return *o.AvailablePages
}

// GetAvailablePagesOk returns a tuple with the AvailablePages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetAvailablePagesOk() (*int64, bool) {
	if o == nil || isNil(o.AvailablePages) {
		return nil, false
	}
	return o.AvailablePages, true
}

// HasAvailablePages returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasAvailablePages() bool {
	if o != nil && !isNil(o.AvailablePages) {
		return true
	}

	return false
}

// SetAvailablePages gets a reference to the given int64 and assigns it to the AvailablePages field.
func (o *PoolsResourceInner) SetAvailablePages(v int64) {
	o.AvailablePages = &v
}

// GetAvailableRfcSize returns the AvailableRfcSize field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetAvailableRfcSize() string {
	if o == nil || isNil(o.AvailableRfcSize) {
		var ret string
		return ret
	}
	return *o.AvailableRfcSize
}

// GetAvailableRfcSizeOk returns a tuple with the AvailableRfcSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetAvailableRfcSizeOk() (*string, bool) {
	if o == nil || isNil(o.AvailableRfcSize) {
		return nil, false
	}
	return o.AvailableRfcSize, true
}

// HasAvailableRfcSize returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasAvailableRfcSize() bool {
	if o != nil && !isNil(o.AvailableRfcSize) {
		return true
	}

	return false
}

// SetAvailableRfcSize gets a reference to the given string and assigns it to the AvailableRfcSize field.
func (o *PoolsResourceInner) SetAvailableRfcSize(v string) {
	o.AvailableRfcSize = &v
}

// GetAvailableRfcSizeNumeric returns the AvailableRfcSizeNumeric field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetAvailableRfcSizeNumeric() int64 {
	if o == nil || isNil(o.AvailableRfcSizeNumeric) {
		var ret int64
		return ret
	}
	return *o.AvailableRfcSizeNumeric
}

// GetAvailableRfcSizeNumericOk returns a tuple with the AvailableRfcSizeNumeric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetAvailableRfcSizeNumericOk() (*int64, bool) {
	if o == nil || isNil(o.AvailableRfcSizeNumeric) {
		return nil, false
	}
	return o.AvailableRfcSizeNumeric, true
}

// HasAvailableRfcSizeNumeric returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasAvailableRfcSizeNumeric() bool {
	if o != nil && !isNil(o.AvailableRfcSizeNumeric) {
		return true
	}

	return false
}

// SetAvailableRfcSizeNumeric gets a reference to the given int64 and assigns it to the AvailableRfcSizeNumeric field.
func (o *PoolsResourceInner) SetAvailableRfcSizeNumeric(v int64) {
	o.AvailableRfcSizeNumeric = &v
}

// GetBlocksize returns the Blocksize field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetBlocksize() int64 {
	if o == nil || isNil(o.Blocksize) {
		var ret int64
		return ret
	}
	return *o.Blocksize
}

// GetBlocksizeOk returns a tuple with the Blocksize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetBlocksizeOk() (*int64, bool) {
	if o == nil || isNil(o.Blocksize) {
		return nil, false
	}
	return o.Blocksize, true
}

// HasBlocksize returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasBlocksize() bool {
	if o != nil && !isNil(o.Blocksize) {
		return true
	}

	return false
}

// SetBlocksize gets a reference to the given int64 and assigns it to the Blocksize field.
func (o *PoolsResourceInner) SetBlocksize(v int64) {
	o.Blocksize = &v
}

// GetCompressionEfficiency returns the CompressionEfficiency field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetCompressionEfficiency() string {
	if o == nil || isNil(o.CompressionEfficiency) {
		var ret string
		return ret
	}
	return *o.CompressionEfficiency
}

// GetCompressionEfficiencyOk returns a tuple with the CompressionEfficiency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetCompressionEfficiencyOk() (*string, bool) {
	if o == nil || isNil(o.CompressionEfficiency) {
		return nil, false
	}
	return o.CompressionEfficiency, true
}

// HasCompressionEfficiency returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasCompressionEfficiency() bool {
	if o != nil && !isNil(o.CompressionEfficiency) {
		return true
	}

	return false
}

// SetCompressionEfficiency gets a reference to the given string and assigns it to the CompressionEfficiency field.
func (o *PoolsResourceInner) SetCompressionEfficiency(v string) {
	o.CompressionEfficiency = &v
}

// GetDiskGroupsCount returns the DiskGroupsCount field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetDiskGroupsCount() int64 {
	if o == nil || isNil(o.DiskGroupsCount) {
		var ret int64
		return ret
	}
	return *o.DiskGroupsCount
}

// GetDiskGroupsCountOk returns a tuple with the DiskGroupsCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetDiskGroupsCountOk() (*int64, bool) {
	if o == nil || isNil(o.DiskGroupsCount) {
		return nil, false
	}
	return o.DiskGroupsCount, true
}

// HasDiskGroupsCount returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasDiskGroupsCount() bool {
	if o != nil && !isNil(o.DiskGroupsCount) {
		return true
	}

	return false
}

// SetDiskGroupsCount gets a reference to the given int64 and assigns it to the DiskGroupsCount field.
func (o *PoolsResourceInner) SetDiskGroupsCount(v int64) {
	o.DiskGroupsCount = &v
}

// GetExtendedStatus returns the ExtendedStatus field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetExtendedStatus() int64 {
	if o == nil || isNil(o.ExtendedStatus) {
		var ret int64
		return ret
	}
	return *o.ExtendedStatus
}

// GetExtendedStatusOk returns a tuple with the ExtendedStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetExtendedStatusOk() (*int64, bool) {
	if o == nil || isNil(o.ExtendedStatus) {
		return nil, false
	}
	return o.ExtendedStatus, true
}

// HasExtendedStatus returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasExtendedStatus() bool {
	if o != nil && !isNil(o.ExtendedStatus) {
		return true
	}

	return false
}

// SetExtendedStatus gets a reference to the given int64 and assigns it to the ExtendedStatus field.
func (o *PoolsResourceInner) SetExtendedStatus(v int64) {
	o.ExtendedStatus = &v
}

// GetHealth returns the Health field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetHealth() string {
	if o == nil || isNil(o.Health) {
		var ret string
		return ret
	}
	return *o.Health
}

// GetHealthOk returns a tuple with the Health field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetHealthOk() (*string, bool) {
	if o == nil || isNil(o.Health) {
		return nil, false
	}
	return o.Health, true
}

// HasHealth returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasHealth() bool {
	if o != nil && !isNil(o.Health) {
		return true
	}

	return false
}

// SetHealth gets a reference to the given string and assigns it to the Health field.
func (o *PoolsResourceInner) SetHealth(v string) {
	o.Health = &v
}

// GetHealthNumeric returns the HealthNumeric field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetHealthNumeric() int64 {
	if o == nil || isNil(o.HealthNumeric) {
		var ret int64
		return ret
	}
	return *o.HealthNumeric
}

// GetHealthNumericOk returns a tuple with the HealthNumeric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetHealthNumericOk() (*int64, bool) {
	if o == nil || isNil(o.HealthNumeric) {
		return nil, false
	}
	return o.HealthNumeric, true
}

// HasHealthNumeric returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasHealthNumeric() bool {
	if o != nil && !isNil(o.HealthNumeric) {
		return true
	}

	return false
}

// SetHealthNumeric gets a reference to the given int64 and assigns it to the HealthNumeric field.
func (o *PoolsResourceInner) SetHealthNumeric(v int64) {
	o.HealthNumeric = &v
}

// GetHealthReason returns the HealthReason field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetHealthReason() string {
	if o == nil || isNil(o.HealthReason) {
		var ret string
		return ret
	}
	return *o.HealthReason
}

// GetHealthReasonOk returns a tuple with the HealthReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetHealthReasonOk() (*string, bool) {
	if o == nil || isNil(o.HealthReason) {
		return nil, false
	}
	return o.HealthReason, true
}

// HasHealthReason returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasHealthReason() bool {
	if o != nil && !isNil(o.HealthReason) {
		return true
	}

	return false
}

// SetHealthReason gets a reference to the given string and assigns it to the HealthReason field.
func (o *PoolsResourceInner) SetHealthReason(v string) {
	o.HealthReason = &v
}

// GetHealthReasonNumeric returns the HealthReasonNumeric field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetHealthReasonNumeric() int64 {
	if o == nil || isNil(o.HealthReasonNumeric) {
		var ret int64
		return ret
	}
	return *o.HealthReasonNumeric
}

// GetHealthReasonNumericOk returns a tuple with the HealthReasonNumeric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetHealthReasonNumericOk() (*int64, bool) {
	if o == nil || isNil(o.HealthReasonNumeric) {
		return nil, false
	}
	return o.HealthReasonNumeric, true
}

// HasHealthReasonNumeric returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasHealthReasonNumeric() bool {
	if o != nil && !isNil(o.HealthReasonNumeric) {
		return true
	}

	return false
}

// SetHealthReasonNumeric gets a reference to the given int64 and assigns it to the HealthReasonNumeric field.
func (o *PoolsResourceInner) SetHealthReasonNumeric(v int64) {
	o.HealthReasonNumeric = &v
}

// GetHealthRecommendation returns the HealthRecommendation field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetHealthRecommendation() string {
	if o == nil || isNil(o.HealthRecommendation) {
		var ret string
		return ret
	}
	return *o.HealthRecommendation
}

// GetHealthRecommendationOk returns a tuple with the HealthRecommendation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetHealthRecommendationOk() (*string, bool) {
	if o == nil || isNil(o.HealthRecommendation) {
		return nil, false
	}
	return o.HealthRecommendation, true
}

// HasHealthRecommendation returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasHealthRecommendation() bool {
	if o != nil && !isNil(o.HealthRecommendation) {
		return true
	}

	return false
}

// SetHealthRecommendation gets a reference to the given string and assigns it to the HealthRecommendation field.
func (o *PoolsResourceInner) SetHealthRecommendation(v string) {
	o.HealthRecommendation = &v
}

// GetHealthRecommendationNumeric returns the HealthRecommendationNumeric field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetHealthRecommendationNumeric() int64 {
	if o == nil || isNil(o.HealthRecommendationNumeric) {
		var ret int64
		return ret
	}
	return *o.HealthRecommendationNumeric
}

// GetHealthRecommendationNumericOk returns a tuple with the HealthRecommendationNumeric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetHealthRecommendationNumericOk() (*int64, bool) {
	if o == nil || isNil(o.HealthRecommendationNumeric) {
		return nil, false
	}
	return o.HealthRecommendationNumeric, true
}

// HasHealthRecommendationNumeric returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasHealthRecommendationNumeric() bool {
	if o != nil && !isNil(o.HealthRecommendationNumeric) {
		return true
	}

	return false
}

// SetHealthRecommendationNumeric gets a reference to the given int64 and assigns it to the HealthRecommendationNumeric field.
func (o *PoolsResourceInner) SetHealthRecommendationNumeric(v int64) {
	o.HealthRecommendationNumeric = &v
}

// GetHighThreshold returns the HighThreshold field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetHighThreshold() string {
	if o == nil || isNil(o.HighThreshold) {
		var ret string
		return ret
	}
	return *o.HighThreshold
}

// GetHighThresholdOk returns a tuple with the HighThreshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetHighThresholdOk() (*string, bool) {
	if o == nil || isNil(o.HighThreshold) {
		return nil, false
	}
	return o.HighThreshold, true
}

// HasHighThreshold returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasHighThreshold() bool {
	if o != nil && !isNil(o.HighThreshold) {
		return true
	}

	return false
}

// SetHighThreshold gets a reference to the given string and assigns it to the HighThreshold field.
func (o *PoolsResourceInner) SetHighThreshold(v string) {
	o.HighThreshold = &v
}

// GetIdlePageCheck returns the IdlePageCheck field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetIdlePageCheck() string {
	if o == nil || isNil(o.IdlePageCheck) {
		var ret string
		return ret
	}
	return *o.IdlePageCheck
}

// GetIdlePageCheckOk returns a tuple with the IdlePageCheck field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetIdlePageCheckOk() (*string, bool) {
	if o == nil || isNil(o.IdlePageCheck) {
		return nil, false
	}
	return o.IdlePageCheck, true
}

// HasIdlePageCheck returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasIdlePageCheck() bool {
	if o != nil && !isNil(o.IdlePageCheck) {
		return true
	}

	return false
}

// SetIdlePageCheck gets a reference to the given string and assigns it to the IdlePageCheck field.
func (o *PoolsResourceInner) SetIdlePageCheck(v string) {
	o.IdlePageCheck = &v
}

// GetIdlePageCheckNumeric returns the IdlePageCheckNumeric field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetIdlePageCheckNumeric() int64 {
	if o == nil || isNil(o.IdlePageCheckNumeric) {
		var ret int64
		return ret
	}
	return *o.IdlePageCheckNumeric
}

// GetIdlePageCheckNumericOk returns a tuple with the IdlePageCheckNumeric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetIdlePageCheckNumericOk() (*int64, bool) {
	if o == nil || isNil(o.IdlePageCheckNumeric) {
		return nil, false
	}
	return o.IdlePageCheckNumeric, true
}

// HasIdlePageCheckNumeric returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasIdlePageCheckNumeric() bool {
	if o != nil && !isNil(o.IdlePageCheckNumeric) {
		return true
	}

	return false
}

// SetIdlePageCheckNumeric gets a reference to the given int64 and assigns it to the IdlePageCheckNumeric field.
func (o *PoolsResourceInner) SetIdlePageCheckNumeric(v int64) {
	o.IdlePageCheckNumeric = &v
}

// GetLowThreshold returns the LowThreshold field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetLowThreshold() string {
	if o == nil || isNil(o.LowThreshold) {
		var ret string
		return ret
	}
	return *o.LowThreshold
}

// GetLowThresholdOk returns a tuple with the LowThreshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetLowThresholdOk() (*string, bool) {
	if o == nil || isNil(o.LowThreshold) {
		return nil, false
	}
	return o.LowThreshold, true
}

// HasLowThreshold returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasLowThreshold() bool {
	if o != nil && !isNil(o.LowThreshold) {
		return true
	}

	return false
}

// SetLowThreshold gets a reference to the given string and assigns it to the LowThreshold field.
func (o *PoolsResourceInner) SetLowThreshold(v string) {
	o.LowThreshold = &v
}

// GetMetadataAllocated returns the MetadataAllocated field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetMetadataAllocated() string {
	if o == nil || isNil(o.MetadataAllocated) {
		var ret string
		return ret
	}
	return *o.MetadataAllocated
}

// GetMetadataAllocatedOk returns a tuple with the MetadataAllocated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetMetadataAllocatedOk() (*string, bool) {
	if o == nil || isNil(o.MetadataAllocated) {
		return nil, false
	}
	return o.MetadataAllocated, true
}

// HasMetadataAllocated returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasMetadataAllocated() bool {
	if o != nil && !isNil(o.MetadataAllocated) {
		return true
	}

	return false
}

// SetMetadataAllocated gets a reference to the given string and assigns it to the MetadataAllocated field.
func (o *PoolsResourceInner) SetMetadataAllocated(v string) {
	o.MetadataAllocated = &v
}

// GetMetadataAllocatedNumeric returns the MetadataAllocatedNumeric field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetMetadataAllocatedNumeric() int64 {
	if o == nil || isNil(o.MetadataAllocatedNumeric) {
		var ret int64
		return ret
	}
	return *o.MetadataAllocatedNumeric
}

// GetMetadataAllocatedNumericOk returns a tuple with the MetadataAllocatedNumeric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetMetadataAllocatedNumericOk() (*int64, bool) {
	if o == nil || isNil(o.MetadataAllocatedNumeric) {
		return nil, false
	}
	return o.MetadataAllocatedNumeric, true
}

// HasMetadataAllocatedNumeric returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasMetadataAllocatedNumeric() bool {
	if o != nil && !isNil(o.MetadataAllocatedNumeric) {
		return true
	}

	return false
}

// SetMetadataAllocatedNumeric gets a reference to the given int64 and assigns it to the MetadataAllocatedNumeric field.
func (o *PoolsResourceInner) SetMetadataAllocatedNumeric(v int64) {
	o.MetadataAllocatedNumeric = &v
}

// GetMetadataAvailable returns the MetadataAvailable field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetMetadataAvailable() string {
	if o == nil || isNil(o.MetadataAvailable) {
		var ret string
		return ret
	}
	return *o.MetadataAvailable
}

// GetMetadataAvailableOk returns a tuple with the MetadataAvailable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetMetadataAvailableOk() (*string, bool) {
	if o == nil || isNil(o.MetadataAvailable) {
		return nil, false
	}
	return o.MetadataAvailable, true
}

// HasMetadataAvailable returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasMetadataAvailable() bool {
	if o != nil && !isNil(o.MetadataAvailable) {
		return true
	}

	return false
}

// SetMetadataAvailable gets a reference to the given string and assigns it to the MetadataAvailable field.
func (o *PoolsResourceInner) SetMetadataAvailable(v string) {
	o.MetadataAvailable = &v
}

// GetMetadataAvailableNumeric returns the MetadataAvailableNumeric field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetMetadataAvailableNumeric() int64 {
	if o == nil || isNil(o.MetadataAvailableNumeric) {
		var ret int64
		return ret
	}
	return *o.MetadataAvailableNumeric
}

// GetMetadataAvailableNumericOk returns a tuple with the MetadataAvailableNumeric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetMetadataAvailableNumericOk() (*int64, bool) {
	if o == nil || isNil(o.MetadataAvailableNumeric) {
		return nil, false
	}
	return o.MetadataAvailableNumeric, true
}

// HasMetadataAvailableNumeric returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasMetadataAvailableNumeric() bool {
	if o != nil && !isNil(o.MetadataAvailableNumeric) {
		return true
	}

	return false
}

// SetMetadataAvailableNumeric gets a reference to the given int64 and assigns it to the MetadataAvailableNumeric field.
func (o *PoolsResourceInner) SetMetadataAvailableNumeric(v int64) {
	o.MetadataAvailableNumeric = &v
}

// GetMetadataTotalSize returns the MetadataTotalSize field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetMetadataTotalSize() string {
	if o == nil || isNil(o.MetadataTotalSize) {
		var ret string
		return ret
	}
	return *o.MetadataTotalSize
}

// GetMetadataTotalSizeOk returns a tuple with the MetadataTotalSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetMetadataTotalSizeOk() (*string, bool) {
	if o == nil || isNil(o.MetadataTotalSize) {
		return nil, false
	}
	return o.MetadataTotalSize, true
}

// HasMetadataTotalSize returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasMetadataTotalSize() bool {
	if o != nil && !isNil(o.MetadataTotalSize) {
		return true
	}

	return false
}

// SetMetadataTotalSize gets a reference to the given string and assigns it to the MetadataTotalSize field.
func (o *PoolsResourceInner) SetMetadataTotalSize(v string) {
	o.MetadataTotalSize = &v
}

// GetMetadataTotalSizeNumeric returns the MetadataTotalSizeNumeric field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetMetadataTotalSizeNumeric() int64 {
	if o == nil || isNil(o.MetadataTotalSizeNumeric) {
		var ret int64
		return ret
	}
	return *o.MetadataTotalSizeNumeric
}

// GetMetadataTotalSizeNumericOk returns a tuple with the MetadataTotalSizeNumeric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetMetadataTotalSizeNumericOk() (*int64, bool) {
	if o == nil || isNil(o.MetadataTotalSizeNumeric) {
		return nil, false
	}
	return o.MetadataTotalSizeNumeric, true
}

// HasMetadataTotalSizeNumeric returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasMetadataTotalSizeNumeric() bool {
	if o != nil && !isNil(o.MetadataTotalSizeNumeric) {
		return true
	}

	return false
}

// SetMetadataTotalSizeNumeric gets a reference to the given int64 and assigns it to the MetadataTotalSizeNumeric field.
func (o *PoolsResourceInner) SetMetadataTotalSizeNumeric(v int64) {
	o.MetadataTotalSizeNumeric = &v
}

// GetMetadataVolSize returns the MetadataVolSize field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetMetadataVolSize() string {
	if o == nil || isNil(o.MetadataVolSize) {
		var ret string
		return ret
	}
	return *o.MetadataVolSize
}

// GetMetadataVolSizeOk returns a tuple with the MetadataVolSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetMetadataVolSizeOk() (*string, bool) {
	if o == nil || isNil(o.MetadataVolSize) {
		return nil, false
	}
	return o.MetadataVolSize, true
}

// HasMetadataVolSize returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasMetadataVolSize() bool {
	if o != nil && !isNil(o.MetadataVolSize) {
		return true
	}

	return false
}

// SetMetadataVolSize gets a reference to the given string and assigns it to the MetadataVolSize field.
func (o *PoolsResourceInner) SetMetadataVolSize(v string) {
	o.MetadataVolSize = &v
}

// GetMetadataVolSizeNumeric returns the MetadataVolSizeNumeric field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetMetadataVolSizeNumeric() int64 {
	if o == nil || isNil(o.MetadataVolSizeNumeric) {
		var ret int64
		return ret
	}
	return *o.MetadataVolSizeNumeric
}

// GetMetadataVolSizeNumericOk returns a tuple with the MetadataVolSizeNumeric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetMetadataVolSizeNumericOk() (*int64, bool) {
	if o == nil || isNil(o.MetadataVolSizeNumeric) {
		return nil, false
	}
	return o.MetadataVolSizeNumeric, true
}

// HasMetadataVolSizeNumeric returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasMetadataVolSizeNumeric() bool {
	if o != nil && !isNil(o.MetadataVolSizeNumeric) {
		return true
	}

	return false
}

// SetMetadataVolSizeNumeric gets a reference to the given int64 and assigns it to the MetadataVolSizeNumeric field.
func (o *PoolsResourceInner) SetMetadataVolSizeNumeric(v int64) {
	o.MetadataVolSizeNumeric = &v
}

// GetMiddleThreshold returns the MiddleThreshold field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetMiddleThreshold() string {
	if o == nil || isNil(o.MiddleThreshold) {
		var ret string
		return ret
	}
	return *o.MiddleThreshold
}

// GetMiddleThresholdOk returns a tuple with the MiddleThreshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetMiddleThresholdOk() (*string, bool) {
	if o == nil || isNil(o.MiddleThreshold) {
		return nil, false
	}
	return o.MiddleThreshold, true
}

// HasMiddleThreshold returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasMiddleThreshold() bool {
	if o != nil && !isNil(o.MiddleThreshold) {
		return true
	}

	return false
}

// SetMiddleThreshold gets a reference to the given string and assigns it to the MiddleThreshold field.
func (o *PoolsResourceInner) SetMiddleThreshold(v string) {
	o.MiddleThreshold = &v
}

// GetMigration returns the Migration field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetMigration() string {
	if o == nil || isNil(o.Migration) {
		var ret string
		return ret
	}
	return *o.Migration
}

// GetMigrationOk returns a tuple with the Migration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetMigrationOk() (*string, bool) {
	if o == nil || isNil(o.Migration) {
		return nil, false
	}
	return o.Migration, true
}

// HasMigration returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasMigration() bool {
	if o != nil && !isNil(o.Migration) {
		return true
	}

	return false
}

// SetMigration gets a reference to the given string and assigns it to the Migration field.
func (o *PoolsResourceInner) SetMigration(v string) {
	o.Migration = &v
}

// GetMigrationNumeric returns the MigrationNumeric field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetMigrationNumeric() int64 {
	if o == nil || isNil(o.MigrationNumeric) {
		var ret int64
		return ret
	}
	return *o.MigrationNumeric
}

// GetMigrationNumericOk returns a tuple with the MigrationNumeric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetMigrationNumericOk() (*int64, bool) {
	if o == nil || isNil(o.MigrationNumeric) {
		return nil, false
	}
	return o.MigrationNumeric, true
}

// HasMigrationNumeric returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasMigrationNumeric() bool {
	if o != nil && !isNil(o.MigrationNumeric) {
		return true
	}

	return false
}

// SetMigrationNumeric gets a reference to the given int64 and assigns it to the MigrationNumeric field.
func (o *PoolsResourceInner) SetMigrationNumeric(v int64) {
	o.MigrationNumeric = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PoolsResourceInner) SetName(v string) {
	o.Name = &v
}

// GetOverCommitted returns the OverCommitted field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetOverCommitted() string {
	if o == nil || isNil(o.OverCommitted) {
		var ret string
		return ret
	}
	return *o.OverCommitted
}

// GetOverCommittedOk returns a tuple with the OverCommitted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetOverCommittedOk() (*string, bool) {
	if o == nil || isNil(o.OverCommitted) {
		return nil, false
	}
	return o.OverCommitted, true
}

// HasOverCommitted returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasOverCommitted() bool {
	if o != nil && !isNil(o.OverCommitted) {
		return true
	}

	return false
}

// SetOverCommitted gets a reference to the given string and assigns it to the OverCommitted field.
func (o *PoolsResourceInner) SetOverCommitted(v string) {
	o.OverCommitted = &v
}

// GetOverCommittedNumeric returns the OverCommittedNumeric field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetOverCommittedNumeric() int64 {
	if o == nil || isNil(o.OverCommittedNumeric) {
		var ret int64
		return ret
	}
	return *o.OverCommittedNumeric
}

// GetOverCommittedNumericOk returns a tuple with the OverCommittedNumeric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetOverCommittedNumericOk() (*int64, bool) {
	if o == nil || isNil(o.OverCommittedNumeric) {
		return nil, false
	}
	return o.OverCommittedNumeric, true
}

// HasOverCommittedNumeric returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasOverCommittedNumeric() bool {
	if o != nil && !isNil(o.OverCommittedNumeric) {
		return true
	}

	return false
}

// SetOverCommittedNumeric gets a reference to the given int64 and assigns it to the OverCommittedNumeric field.
func (o *PoolsResourceInner) SetOverCommittedNumeric(v int64) {
	o.OverCommittedNumeric = &v
}

// GetOvercommit returns the Overcommit field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetOvercommit() string {
	if o == nil || isNil(o.Overcommit) {
		var ret string
		return ret
	}
	return *o.Overcommit
}

// GetOvercommitOk returns a tuple with the Overcommit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetOvercommitOk() (*string, bool) {
	if o == nil || isNil(o.Overcommit) {
		return nil, false
	}
	return o.Overcommit, true
}

// HasOvercommit returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasOvercommit() bool {
	if o != nil && !isNil(o.Overcommit) {
		return true
	}

	return false
}

// SetOvercommit gets a reference to the given string and assigns it to the Overcommit field.
func (o *PoolsResourceInner) SetOvercommit(v string) {
	o.Overcommit = &v
}

// GetOvercommitNumeric returns the OvercommitNumeric field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetOvercommitNumeric() int64 {
	if o == nil || isNil(o.OvercommitNumeric) {
		var ret int64
		return ret
	}
	return *o.OvercommitNumeric
}

// GetOvercommitNumericOk returns a tuple with the OvercommitNumeric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetOvercommitNumericOk() (*int64, bool) {
	if o == nil || isNil(o.OvercommitNumeric) {
		return nil, false
	}
	return o.OvercommitNumeric, true
}

// HasOvercommitNumeric returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasOvercommitNumeric() bool {
	if o != nil && !isNil(o.OvercommitNumeric) {
		return true
	}

	return false
}

// SetOvercommitNumeric gets a reference to the given int64 and assigns it to the OvercommitNumeric field.
func (o *PoolsResourceInner) SetOvercommitNumeric(v int64) {
	o.OvercommitNumeric = &v
}

// GetOwner returns the Owner field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetOwner() string {
	if o == nil || isNil(o.Owner) {
		var ret string
		return ret
	}
	return *o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetOwnerOk() (*string, bool) {
	if o == nil || isNil(o.Owner) {
		return nil, false
	}
	return o.Owner, true
}

// HasOwner returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasOwner() bool {
	if o != nil && !isNil(o.Owner) {
		return true
	}

	return false
}

// SetOwner gets a reference to the given string and assigns it to the Owner field.
func (o *PoolsResourceInner) SetOwner(v string) {
	o.Owner = &v
}

// GetOwnerNumeric returns the OwnerNumeric field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetOwnerNumeric() int64 {
	if o == nil || isNil(o.OwnerNumeric) {
		var ret int64
		return ret
	}
	return *o.OwnerNumeric
}

// GetOwnerNumericOk returns a tuple with the OwnerNumeric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetOwnerNumericOk() (*int64, bool) {
	if o == nil || isNil(o.OwnerNumeric) {
		return nil, false
	}
	return o.OwnerNumeric, true
}

// HasOwnerNumeric returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasOwnerNumeric() bool {
	if o != nil && !isNil(o.OwnerNumeric) {
		return true
	}

	return false
}

// SetOwnerNumeric gets a reference to the given int64 and assigns it to the OwnerNumeric field.
func (o *PoolsResourceInner) SetOwnerNumeric(v int64) {
	o.OwnerNumeric = &v
}

// GetPageSize returns the PageSize field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetPageSize() string {
	if o == nil || isNil(o.PageSize) {
		var ret string
		return ret
	}
	return *o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetPageSizeOk() (*string, bool) {
	if o == nil || isNil(o.PageSize) {
		return nil, false
	}
	return o.PageSize, true
}

// HasPageSize returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasPageSize() bool {
	if o != nil && !isNil(o.PageSize) {
		return true
	}

	return false
}

// SetPageSize gets a reference to the given string and assigns it to the PageSize field.
func (o *PoolsResourceInner) SetPageSize(v string) {
	o.PageSize = &v
}

// GetPageSizeNumeric returns the PageSizeNumeric field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetPageSizeNumeric() int64 {
	if o == nil || isNil(o.PageSizeNumeric) {
		var ret int64
		return ret
	}
	return *o.PageSizeNumeric
}

// GetPageSizeNumericOk returns a tuple with the PageSizeNumeric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetPageSizeNumericOk() (*int64, bool) {
	if o == nil || isNil(o.PageSizeNumeric) {
		return nil, false
	}
	return o.PageSizeNumeric, true
}

// HasPageSizeNumeric returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasPageSizeNumeric() bool {
	if o != nil && !isNil(o.PageSizeNumeric) {
		return true
	}

	return false
}

// SetPageSizeNumeric gets a reference to the given int64 and assigns it to the PageSizeNumeric field.
func (o *PoolsResourceInner) SetPageSizeNumeric(v int64) {
	o.PageSizeNumeric = &v
}

// GetPoolSectorFormat returns the PoolSectorFormat field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetPoolSectorFormat() string {
	if o == nil || isNil(o.PoolSectorFormat) {
		var ret string
		return ret
	}
	return *o.PoolSectorFormat
}

// GetPoolSectorFormatOk returns a tuple with the PoolSectorFormat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetPoolSectorFormatOk() (*string, bool) {
	if o == nil || isNil(o.PoolSectorFormat) {
		return nil, false
	}
	return o.PoolSectorFormat, true
}

// HasPoolSectorFormat returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasPoolSectorFormat() bool {
	if o != nil && !isNil(o.PoolSectorFormat) {
		return true
	}

	return false
}

// SetPoolSectorFormat gets a reference to the given string and assigns it to the PoolSectorFormat field.
func (o *PoolsResourceInner) SetPoolSectorFormat(v string) {
	o.PoolSectorFormat = &v
}

// GetPoolSectorFormatNumeric returns the PoolSectorFormatNumeric field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetPoolSectorFormatNumeric() int64 {
	if o == nil || isNil(o.PoolSectorFormatNumeric) {
		var ret int64
		return ret
	}
	return *o.PoolSectorFormatNumeric
}

// GetPoolSectorFormatNumericOk returns a tuple with the PoolSectorFormatNumeric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetPoolSectorFormatNumericOk() (*int64, bool) {
	if o == nil || isNil(o.PoolSectorFormatNumeric) {
		return nil, false
	}
	return o.PoolSectorFormatNumeric, true
}

// HasPoolSectorFormatNumeric returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasPoolSectorFormatNumeric() bool {
	if o != nil && !isNil(o.PoolSectorFormatNumeric) {
		return true
	}

	return false
}

// SetPoolSectorFormatNumeric gets a reference to the given int64 and assigns it to the PoolSectorFormatNumeric field.
func (o *PoolsResourceInner) SetPoolSectorFormatNumeric(v int64) {
	o.PoolSectorFormatNumeric = &v
}

// GetPreferredOwner returns the PreferredOwner field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetPreferredOwner() string {
	if o == nil || isNil(o.PreferredOwner) {
		var ret string
		return ret
	}
	return *o.PreferredOwner
}

// GetPreferredOwnerOk returns a tuple with the PreferredOwner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetPreferredOwnerOk() (*string, bool) {
	if o == nil || isNil(o.PreferredOwner) {
		return nil, false
	}
	return o.PreferredOwner, true
}

// HasPreferredOwner returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasPreferredOwner() bool {
	if o != nil && !isNil(o.PreferredOwner) {
		return true
	}

	return false
}

// SetPreferredOwner gets a reference to the given string and assigns it to the PreferredOwner field.
func (o *PoolsResourceInner) SetPreferredOwner(v string) {
	o.PreferredOwner = &v
}

// GetPreferredOwnerNumeric returns the PreferredOwnerNumeric field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetPreferredOwnerNumeric() int64 {
	if o == nil || isNil(o.PreferredOwnerNumeric) {
		var ret int64
		return ret
	}
	return *o.PreferredOwnerNumeric
}

// GetPreferredOwnerNumericOk returns a tuple with the PreferredOwnerNumeric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetPreferredOwnerNumericOk() (*int64, bool) {
	if o == nil || isNil(o.PreferredOwnerNumeric) {
		return nil, false
	}
	return o.PreferredOwnerNumeric, true
}

// HasPreferredOwnerNumeric returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasPreferredOwnerNumeric() bool {
	if o != nil && !isNil(o.PreferredOwnerNumeric) {
		return true
	}

	return false
}

// SetPreferredOwnerNumeric gets a reference to the given int64 and assigns it to the PreferredOwnerNumeric field.
func (o *PoolsResourceInner) SetPreferredOwnerNumeric(v int64) {
	o.PreferredOwnerNumeric = &v
}

// GetReadFlashCache returns the ReadFlashCache field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetReadFlashCache() string {
	if o == nil || isNil(o.ReadFlashCache) {
		var ret string
		return ret
	}
	return *o.ReadFlashCache
}

// GetReadFlashCacheOk returns a tuple with the ReadFlashCache field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetReadFlashCacheOk() (*string, bool) {
	if o == nil || isNil(o.ReadFlashCache) {
		return nil, false
	}
	return o.ReadFlashCache, true
}

// HasReadFlashCache returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasReadFlashCache() bool {
	if o != nil && !isNil(o.ReadFlashCache) {
		return true
	}

	return false
}

// SetReadFlashCache gets a reference to the given string and assigns it to the ReadFlashCache field.
func (o *PoolsResourceInner) SetReadFlashCache(v string) {
	o.ReadFlashCache = &v
}

// GetReadFlashCacheNumeric returns the ReadFlashCacheNumeric field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetReadFlashCacheNumeric() int64 {
	if o == nil || isNil(o.ReadFlashCacheNumeric) {
		var ret int64
		return ret
	}
	return *o.ReadFlashCacheNumeric
}

// GetReadFlashCacheNumericOk returns a tuple with the ReadFlashCacheNumeric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetReadFlashCacheNumericOk() (*int64, bool) {
	if o == nil || isNil(o.ReadFlashCacheNumeric) {
		return nil, false
	}
	return o.ReadFlashCacheNumeric, true
}

// HasReadFlashCacheNumeric returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasReadFlashCacheNumeric() bool {
	if o != nil && !isNil(o.ReadFlashCacheNumeric) {
		return true
	}

	return false
}

// SetReadFlashCacheNumeric gets a reference to the given int64 and assigns it to the ReadFlashCacheNumeric field.
func (o *PoolsResourceInner) SetReadFlashCacheNumeric(v int64) {
	o.ReadFlashCacheNumeric = &v
}

// GetRebalance returns the Rebalance field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetRebalance() string {
	if o == nil || isNil(o.Rebalance) {
		var ret string
		return ret
	}
	return *o.Rebalance
}

// GetRebalanceOk returns a tuple with the Rebalance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetRebalanceOk() (*string, bool) {
	if o == nil || isNil(o.Rebalance) {
		return nil, false
	}
	return o.Rebalance, true
}

// HasRebalance returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasRebalance() bool {
	if o != nil && !isNil(o.Rebalance) {
		return true
	}

	return false
}

// SetRebalance gets a reference to the given string and assigns it to the Rebalance field.
func (o *PoolsResourceInner) SetRebalance(v string) {
	o.Rebalance = &v
}

// GetRebalanceNumeric returns the RebalanceNumeric field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetRebalanceNumeric() int64 {
	if o == nil || isNil(o.RebalanceNumeric) {
		var ret int64
		return ret
	}
	return *o.RebalanceNumeric
}

// GetRebalanceNumericOk returns a tuple with the RebalanceNumeric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetRebalanceNumericOk() (*int64, bool) {
	if o == nil || isNil(o.RebalanceNumeric) {
		return nil, false
	}
	return o.RebalanceNumeric, true
}

// HasRebalanceNumeric returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasRebalanceNumeric() bool {
	if o != nil && !isNil(o.RebalanceNumeric) {
		return true
	}

	return false
}

// SetRebalanceNumeric gets a reference to the given int64 and assigns it to the RebalanceNumeric field.
func (o *PoolsResourceInner) SetRebalanceNumeric(v int64) {
	o.RebalanceNumeric = &v
}

// GetReservedSize returns the ReservedSize field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetReservedSize() string {
	if o == nil || isNil(o.ReservedSize) {
		var ret string
		return ret
	}
	return *o.ReservedSize
}

// GetReservedSizeOk returns a tuple with the ReservedSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetReservedSizeOk() (*string, bool) {
	if o == nil || isNil(o.ReservedSize) {
		return nil, false
	}
	return o.ReservedSize, true
}

// HasReservedSize returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasReservedSize() bool {
	if o != nil && !isNil(o.ReservedSize) {
		return true
	}

	return false
}

// SetReservedSize gets a reference to the given string and assigns it to the ReservedSize field.
func (o *PoolsResourceInner) SetReservedSize(v string) {
	o.ReservedSize = &v
}

// GetReservedSizeNumeric returns the ReservedSizeNumeric field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetReservedSizeNumeric() int64 {
	if o == nil || isNil(o.ReservedSizeNumeric) {
		var ret int64
		return ret
	}
	return *o.ReservedSizeNumeric
}

// GetReservedSizeNumericOk returns a tuple with the ReservedSizeNumeric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetReservedSizeNumericOk() (*int64, bool) {
	if o == nil || isNil(o.ReservedSizeNumeric) {
		return nil, false
	}
	return o.ReservedSizeNumeric, true
}

// HasReservedSizeNumeric returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasReservedSizeNumeric() bool {
	if o != nil && !isNil(o.ReservedSizeNumeric) {
		return true
	}

	return false
}

// SetReservedSizeNumeric gets a reference to the given int64 and assigns it to the ReservedSizeNumeric field.
func (o *PoolsResourceInner) SetReservedSizeNumeric(v int64) {
	o.ReservedSizeNumeric = &v
}

// GetReservedUnallocSize returns the ReservedUnallocSize field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetReservedUnallocSize() string {
	if o == nil || isNil(o.ReservedUnallocSize) {
		var ret string
		return ret
	}
	return *o.ReservedUnallocSize
}

// GetReservedUnallocSizeOk returns a tuple with the ReservedUnallocSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetReservedUnallocSizeOk() (*string, bool) {
	if o == nil || isNil(o.ReservedUnallocSize) {
		return nil, false
	}
	return o.ReservedUnallocSize, true
}

// HasReservedUnallocSize returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasReservedUnallocSize() bool {
	if o != nil && !isNil(o.ReservedUnallocSize) {
		return true
	}

	return false
}

// SetReservedUnallocSize gets a reference to the given string and assigns it to the ReservedUnallocSize field.
func (o *PoolsResourceInner) SetReservedUnallocSize(v string) {
	o.ReservedUnallocSize = &v
}

// GetReservedUnallocSizeNumeric returns the ReservedUnallocSizeNumeric field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetReservedUnallocSizeNumeric() int64 {
	if o == nil || isNil(o.ReservedUnallocSizeNumeric) {
		var ret int64
		return ret
	}
	return *o.ReservedUnallocSizeNumeric
}

// GetReservedUnallocSizeNumericOk returns a tuple with the ReservedUnallocSizeNumeric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetReservedUnallocSizeNumericOk() (*int64, bool) {
	if o == nil || isNil(o.ReservedUnallocSizeNumeric) {
		return nil, false
	}
	return o.ReservedUnallocSizeNumeric, true
}

// HasReservedUnallocSizeNumeric returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasReservedUnallocSizeNumeric() bool {
	if o != nil && !isNil(o.ReservedUnallocSizeNumeric) {
		return true
	}

	return false
}

// SetReservedUnallocSizeNumeric gets a reference to the given int64 and assigns it to the ReservedUnallocSizeNumeric field.
func (o *PoolsResourceInner) SetReservedUnallocSizeNumeric(v int64) {
	o.ReservedUnallocSizeNumeric = &v
}

// GetSerialNumber returns the SerialNumber field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetSerialNumber() string {
	if o == nil || isNil(o.SerialNumber) {
		var ret string
		return ret
	}
	return *o.SerialNumber
}

// GetSerialNumberOk returns a tuple with the SerialNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetSerialNumberOk() (*string, bool) {
	if o == nil || isNil(o.SerialNumber) {
		return nil, false
	}
	return o.SerialNumber, true
}

// HasSerialNumber returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasSerialNumber() bool {
	if o != nil && !isNil(o.SerialNumber) {
		return true
	}

	return false
}

// SetSerialNumber gets a reference to the given string and assigns it to the SerialNumber field.
func (o *PoolsResourceInner) SetSerialNumber(v string) {
	o.SerialNumber = &v
}

// GetSnapSize returns the SnapSize field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetSnapSize() string {
	if o == nil || isNil(o.SnapSize) {
		var ret string
		return ret
	}
	return *o.SnapSize
}

// GetSnapSizeOk returns a tuple with the SnapSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetSnapSizeOk() (*string, bool) {
	if o == nil || isNil(o.SnapSize) {
		return nil, false
	}
	return o.SnapSize, true
}

// HasSnapSize returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasSnapSize() bool {
	if o != nil && !isNil(o.SnapSize) {
		return true
	}

	return false
}

// SetSnapSize gets a reference to the given string and assigns it to the SnapSize field.
func (o *PoolsResourceInner) SetSnapSize(v string) {
	o.SnapSize = &v
}

// GetSnapSizeNumeric returns the SnapSizeNumeric field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetSnapSizeNumeric() int64 {
	if o == nil || isNil(o.SnapSizeNumeric) {
		var ret int64
		return ret
	}
	return *o.SnapSizeNumeric
}

// GetSnapSizeNumericOk returns a tuple with the SnapSizeNumeric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetSnapSizeNumericOk() (*int64, bool) {
	if o == nil || isNil(o.SnapSizeNumeric) {
		return nil, false
	}
	return o.SnapSizeNumeric, true
}

// HasSnapSizeNumeric returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasSnapSizeNumeric() bool {
	if o != nil && !isNil(o.SnapSizeNumeric) {
		return true
	}

	return false
}

// SetSnapSizeNumeric gets a reference to the given int64 and assigns it to the SnapSizeNumeric field.
func (o *PoolsResourceInner) SetSnapSizeNumeric(v int64) {
	o.SnapSizeNumeric = &v
}

// GetStorageType returns the StorageType field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetStorageType() string {
	if o == nil || isNil(o.StorageType) {
		var ret string
		return ret
	}
	return *o.StorageType
}

// GetStorageTypeOk returns a tuple with the StorageType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetStorageTypeOk() (*string, bool) {
	if o == nil || isNil(o.StorageType) {
		return nil, false
	}
	return o.StorageType, true
}

// HasStorageType returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasStorageType() bool {
	if o != nil && !isNil(o.StorageType) {
		return true
	}

	return false
}

// SetStorageType gets a reference to the given string and assigns it to the StorageType field.
func (o *PoolsResourceInner) SetStorageType(v string) {
	o.StorageType = &v
}

// GetStorageTypeNumeric returns the StorageTypeNumeric field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetStorageTypeNumeric() int64 {
	if o == nil || isNil(o.StorageTypeNumeric) {
		var ret int64
		return ret
	}
	return *o.StorageTypeNumeric
}

// GetStorageTypeNumericOk returns a tuple with the StorageTypeNumeric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetStorageTypeNumericOk() (*int64, bool) {
	if o == nil || isNil(o.StorageTypeNumeric) {
		return nil, false
	}
	return o.StorageTypeNumeric, true
}

// HasStorageTypeNumeric returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasStorageTypeNumeric() bool {
	if o != nil && !isNil(o.StorageTypeNumeric) {
		return true
	}

	return false
}

// SetStorageTypeNumeric gets a reference to the given int64 and assigns it to the StorageTypeNumeric field.
func (o *PoolsResourceInner) SetStorageTypeNumeric(v int64) {
	o.StorageTypeNumeric = &v
}

// GetTotalAvail returns the TotalAvail field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetTotalAvail() string {
	if o == nil || isNil(o.TotalAvail) {
		var ret string
		return ret
	}
	return *o.TotalAvail
}

// GetTotalAvailOk returns a tuple with the TotalAvail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetTotalAvailOk() (*string, bool) {
	if o == nil || isNil(o.TotalAvail) {
		return nil, false
	}
	return o.TotalAvail, true
}

// HasTotalAvail returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasTotalAvail() bool {
	if o != nil && !isNil(o.TotalAvail) {
		return true
	}

	return false
}

// SetTotalAvail gets a reference to the given string and assigns it to the TotalAvail field.
func (o *PoolsResourceInner) SetTotalAvail(v string) {
	o.TotalAvail = &v
}

// GetTotalAvailNumeric returns the TotalAvailNumeric field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetTotalAvailNumeric() int64 {
	if o == nil || isNil(o.TotalAvailNumeric) {
		var ret int64
		return ret
	}
	return *o.TotalAvailNumeric
}

// GetTotalAvailNumericOk returns a tuple with the TotalAvailNumeric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetTotalAvailNumericOk() (*int64, bool) {
	if o == nil || isNil(o.TotalAvailNumeric) {
		return nil, false
	}
	return o.TotalAvailNumeric, true
}

// HasTotalAvailNumeric returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasTotalAvailNumeric() bool {
	if o != nil && !isNil(o.TotalAvailNumeric) {
		return true
	}

	return false
}

// SetTotalAvailNumeric gets a reference to the given int64 and assigns it to the TotalAvailNumeric field.
func (o *PoolsResourceInner) SetTotalAvailNumeric(v int64) {
	o.TotalAvailNumeric = &v
}

// GetTotalRfcSize returns the TotalRfcSize field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetTotalRfcSize() string {
	if o == nil || isNil(o.TotalRfcSize) {
		var ret string
		return ret
	}
	return *o.TotalRfcSize
}

// GetTotalRfcSizeOk returns a tuple with the TotalRfcSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetTotalRfcSizeOk() (*string, bool) {
	if o == nil || isNil(o.TotalRfcSize) {
		return nil, false
	}
	return o.TotalRfcSize, true
}

// HasTotalRfcSize returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasTotalRfcSize() bool {
	if o != nil && !isNil(o.TotalRfcSize) {
		return true
	}

	return false
}

// SetTotalRfcSize gets a reference to the given string and assigns it to the TotalRfcSize field.
func (o *PoolsResourceInner) SetTotalRfcSize(v string) {
	o.TotalRfcSize = &v
}

// GetTotalRfcSizeNumeric returns the TotalRfcSizeNumeric field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetTotalRfcSizeNumeric() int64 {
	if o == nil || isNil(o.TotalRfcSizeNumeric) {
		var ret int64
		return ret
	}
	return *o.TotalRfcSizeNumeric
}

// GetTotalRfcSizeNumericOk returns a tuple with the TotalRfcSizeNumeric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetTotalRfcSizeNumericOk() (*int64, bool) {
	if o == nil || isNil(o.TotalRfcSizeNumeric) {
		return nil, false
	}
	return o.TotalRfcSizeNumeric, true
}

// HasTotalRfcSizeNumeric returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasTotalRfcSizeNumeric() bool {
	if o != nil && !isNil(o.TotalRfcSizeNumeric) {
		return true
	}

	return false
}

// SetTotalRfcSizeNumeric gets a reference to the given int64 and assigns it to the TotalRfcSizeNumeric field.
func (o *PoolsResourceInner) SetTotalRfcSizeNumeric(v int64) {
	o.TotalRfcSizeNumeric = &v
}

// GetTotalSize returns the TotalSize field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetTotalSize() string {
	if o == nil || isNil(o.TotalSize) {
		var ret string
		return ret
	}
	return *o.TotalSize
}

// GetTotalSizeOk returns a tuple with the TotalSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetTotalSizeOk() (*string, bool) {
	if o == nil || isNil(o.TotalSize) {
		return nil, false
	}
	return o.TotalSize, true
}

// HasTotalSize returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasTotalSize() bool {
	if o != nil && !isNil(o.TotalSize) {
		return true
	}

	return false
}

// SetTotalSize gets a reference to the given string and assigns it to the TotalSize field.
func (o *PoolsResourceInner) SetTotalSize(v string) {
	o.TotalSize = &v
}

// GetTotalSizeNumeric returns the TotalSizeNumeric field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetTotalSizeNumeric() int64 {
	if o == nil || isNil(o.TotalSizeNumeric) {
		var ret int64
		return ret
	}
	return *o.TotalSizeNumeric
}

// GetTotalSizeNumericOk returns a tuple with the TotalSizeNumeric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetTotalSizeNumericOk() (*int64, bool) {
	if o == nil || isNil(o.TotalSizeNumeric) {
		return nil, false
	}
	return o.TotalSizeNumeric, true
}

// HasTotalSizeNumeric returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasTotalSizeNumeric() bool {
	if o != nil && !isNil(o.TotalSizeNumeric) {
		return true
	}

	return false
}

// SetTotalSizeNumeric gets a reference to the given int64 and assigns it to the TotalSizeNumeric field.
func (o *PoolsResourceInner) SetTotalSizeNumeric(v int64) {
	o.TotalSizeNumeric = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetUrl() string {
	if o == nil || isNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetUrlOk() (*string, bool) {
	if o == nil || isNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasUrl() bool {
	if o != nil && !isNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *PoolsResourceInner) SetUrl(v string) {
	o.Url = &v
}

// GetUtilityRunning returns the UtilityRunning field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetUtilityRunning() string {
	if o == nil || isNil(o.UtilityRunning) {
		var ret string
		return ret
	}
	return *o.UtilityRunning
}

// GetUtilityRunningOk returns a tuple with the UtilityRunning field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetUtilityRunningOk() (*string, bool) {
	if o == nil || isNil(o.UtilityRunning) {
		return nil, false
	}
	return o.UtilityRunning, true
}

// HasUtilityRunning returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasUtilityRunning() bool {
	if o != nil && !isNil(o.UtilityRunning) {
		return true
	}

	return false
}

// SetUtilityRunning gets a reference to the given string and assigns it to the UtilityRunning field.
func (o *PoolsResourceInner) SetUtilityRunning(v string) {
	o.UtilityRunning = &v
}

// GetUtilityRunningNumeric returns the UtilityRunningNumeric field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetUtilityRunningNumeric() int64 {
	if o == nil || isNil(o.UtilityRunningNumeric) {
		var ret int64
		return ret
	}
	return *o.UtilityRunningNumeric
}

// GetUtilityRunningNumericOk returns a tuple with the UtilityRunningNumeric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetUtilityRunningNumericOk() (*int64, bool) {
	if o == nil || isNil(o.UtilityRunningNumeric) {
		return nil, false
	}
	return o.UtilityRunningNumeric, true
}

// HasUtilityRunningNumeric returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasUtilityRunningNumeric() bool {
	if o != nil && !isNil(o.UtilityRunningNumeric) {
		return true
	}

	return false
}

// SetUtilityRunningNumeric gets a reference to the given int64 and assigns it to the UtilityRunningNumeric field.
func (o *PoolsResourceInner) SetUtilityRunningNumeric(v int64) {
	o.UtilityRunningNumeric = &v
}

// GetVolumes returns the Volumes field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetVolumes() int64 {
	if o == nil || isNil(o.Volumes) {
		var ret int64
		return ret
	}
	return *o.Volumes
}

// GetVolumesOk returns a tuple with the Volumes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetVolumesOk() (*int64, bool) {
	if o == nil || isNil(o.Volumes) {
		return nil, false
	}
	return o.Volumes, true
}

// HasVolumes returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasVolumes() bool {
	if o != nil && !isNil(o.Volumes) {
		return true
	}

	return false
}

// SetVolumes gets a reference to the given int64 and assigns it to the Volumes field.
func (o *PoolsResourceInner) SetVolumes(v int64) {
	o.Volumes = &v
}

// GetZeroScan returns the ZeroScan field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetZeroScan() string {
	if o == nil || isNil(o.ZeroScan) {
		var ret string
		return ret
	}
	return *o.ZeroScan
}

// GetZeroScanOk returns a tuple with the ZeroScan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetZeroScanOk() (*string, bool) {
	if o == nil || isNil(o.ZeroScan) {
		return nil, false
	}
	return o.ZeroScan, true
}

// HasZeroScan returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasZeroScan() bool {
	if o != nil && !isNil(o.ZeroScan) {
		return true
	}

	return false
}

// SetZeroScan gets a reference to the given string and assigns it to the ZeroScan field.
func (o *PoolsResourceInner) SetZeroScan(v string) {
	o.ZeroScan = &v
}

// GetZeroScanNumeric returns the ZeroScanNumeric field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetZeroScanNumeric() int64 {
	if o == nil || isNil(o.ZeroScanNumeric) {
		var ret int64
		return ret
	}
	return *o.ZeroScanNumeric
}

// GetZeroScanNumericOk returns a tuple with the ZeroScanNumeric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetZeroScanNumericOk() (*int64, bool) {
	if o == nil || isNil(o.ZeroScanNumeric) {
		return nil, false
	}
	return o.ZeroScanNumeric, true
}

// HasZeroScanNumeric returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasZeroScanNumeric() bool {
	if o != nil && !isNil(o.ZeroScanNumeric) {
		return true
	}

	return false
}

// SetZeroScanNumeric gets a reference to the given int64 and assigns it to the ZeroScanNumeric field.
func (o *PoolsResourceInner) SetZeroScanNumeric(v int64) {
	o.ZeroScanNumeric = &v
}

// GetDiskGroups returns the DiskGroups field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetDiskGroups() []DiskGroupsResourceInner {
	if o == nil || isNil(o.DiskGroups) {
		var ret []DiskGroupsResourceInner
		return ret
	}
	return o.DiskGroups
}

// GetDiskGroupsOk returns a tuple with the DiskGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetDiskGroupsOk() ([]DiskGroupsResourceInner, bool) {
	if o == nil || isNil(o.DiskGroups) {
		return nil, false
	}
	return o.DiskGroups, true
}

// HasDiskGroups returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasDiskGroups() bool {
	if o != nil && !isNil(o.DiskGroups) {
		return true
	}

	return false
}

// SetDiskGroups gets a reference to the given []DiskGroupsResourceInner and assigns it to the DiskGroups field.
func (o *PoolsResourceInner) SetDiskGroups(v []DiskGroupsResourceInner) {
	o.DiskGroups = v
}

// GetTiers returns the Tiers field value if set, zero value otherwise.
func (o *PoolsResourceInner) GetTiers() []TiersResourceInner {
	if o == nil || isNil(o.Tiers) {
		var ret []TiersResourceInner
		return ret
	}
	return o.Tiers
}

// GetTiersOk returns a tuple with the Tiers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoolsResourceInner) GetTiersOk() ([]TiersResourceInner, bool) {
	if o == nil || isNil(o.Tiers) {
		return nil, false
	}
	return o.Tiers, true
}

// HasTiers returns a boolean if a field has been set.
func (o *PoolsResourceInner) HasTiers() bool {
	if o != nil && !isNil(o.Tiers) {
		return true
	}

	return false
}

// SetTiers gets a reference to the given []TiersResourceInner and assigns it to the Tiers field.
func (o *PoolsResourceInner) SetTiers(v []TiersResourceInner) {
	o.Tiers = v
}

func (o PoolsResourceInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.ObjectName) {
		toSerialize["object-name"] = o.ObjectName
	}
	if !isNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	if !isNil(o.AllocatedPages) {
		toSerialize["allocated-pages"] = o.AllocatedPages
	}
	if !isNil(o.AvailablePages) {
		toSerialize["available-pages"] = o.AvailablePages
	}
	if !isNil(o.AvailableRfcSize) {
		toSerialize["available-rfc-size"] = o.AvailableRfcSize
	}
	if !isNil(o.AvailableRfcSizeNumeric) {
		toSerialize["available-rfc-size-numeric"] = o.AvailableRfcSizeNumeric
	}
	if !isNil(o.Blocksize) {
		toSerialize["blocksize"] = o.Blocksize
	}
	if !isNil(o.CompressionEfficiency) {
		toSerialize["compression-efficiency"] = o.CompressionEfficiency
	}
	if !isNil(o.DiskGroupsCount) {
		toSerialize["disk-groups-count"] = o.DiskGroupsCount
	}
	if !isNil(o.ExtendedStatus) {
		toSerialize["extended-status"] = o.ExtendedStatus
	}
	if !isNil(o.Health) {
		toSerialize["health"] = o.Health
	}
	if !isNil(o.HealthNumeric) {
		toSerialize["health-numeric"] = o.HealthNumeric
	}
	if !isNil(o.HealthReason) {
		toSerialize["health-reason"] = o.HealthReason
	}
	if !isNil(o.HealthReasonNumeric) {
		toSerialize["health-reason-numeric"] = o.HealthReasonNumeric
	}
	if !isNil(o.HealthRecommendation) {
		toSerialize["health-recommendation"] = o.HealthRecommendation
	}
	if !isNil(o.HealthRecommendationNumeric) {
		toSerialize["health-recommendation-numeric"] = o.HealthRecommendationNumeric
	}
	if !isNil(o.HighThreshold) {
		toSerialize["high-threshold"] = o.HighThreshold
	}
	if !isNil(o.IdlePageCheck) {
		toSerialize["idle-page-check"] = o.IdlePageCheck
	}
	if !isNil(o.IdlePageCheckNumeric) {
		toSerialize["idle-page-check-numeric"] = o.IdlePageCheckNumeric
	}
	if !isNil(o.LowThreshold) {
		toSerialize["low-threshold"] = o.LowThreshold
	}
	if !isNil(o.MetadataAllocated) {
		toSerialize["metadata-allocated"] = o.MetadataAllocated
	}
	if !isNil(o.MetadataAllocatedNumeric) {
		toSerialize["metadata-allocated-numeric"] = o.MetadataAllocatedNumeric
	}
	if !isNil(o.MetadataAvailable) {
		toSerialize["metadata-available"] = o.MetadataAvailable
	}
	if !isNil(o.MetadataAvailableNumeric) {
		toSerialize["metadata-available-numeric"] = o.MetadataAvailableNumeric
	}
	if !isNil(o.MetadataTotalSize) {
		toSerialize["metadata-total-size"] = o.MetadataTotalSize
	}
	if !isNil(o.MetadataTotalSizeNumeric) {
		toSerialize["metadata-total-size-numeric"] = o.MetadataTotalSizeNumeric
	}
	if !isNil(o.MetadataVolSize) {
		toSerialize["metadata-vol-size"] = o.MetadataVolSize
	}
	if !isNil(o.MetadataVolSizeNumeric) {
		toSerialize["metadata-vol-size-numeric"] = o.MetadataVolSizeNumeric
	}
	if !isNil(o.MiddleThreshold) {
		toSerialize["middle-threshold"] = o.MiddleThreshold
	}
	if !isNil(o.Migration) {
		toSerialize["migration"] = o.Migration
	}
	if !isNil(o.MigrationNumeric) {
		toSerialize["migration-numeric"] = o.MigrationNumeric
	}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !isNil(o.OverCommitted) {
		toSerialize["over-committed"] = o.OverCommitted
	}
	if !isNil(o.OverCommittedNumeric) {
		toSerialize["over-committed-numeric"] = o.OverCommittedNumeric
	}
	if !isNil(o.Overcommit) {
		toSerialize["overcommit"] = o.Overcommit
	}
	if !isNil(o.OvercommitNumeric) {
		toSerialize["overcommit-numeric"] = o.OvercommitNumeric
	}
	if !isNil(o.Owner) {
		toSerialize["owner"] = o.Owner
	}
	if !isNil(o.OwnerNumeric) {
		toSerialize["owner-numeric"] = o.OwnerNumeric
	}
	if !isNil(o.PageSize) {
		toSerialize["page-size"] = o.PageSize
	}
	if !isNil(o.PageSizeNumeric) {
		toSerialize["page-size-numeric"] = o.PageSizeNumeric
	}
	if !isNil(o.PoolSectorFormat) {
		toSerialize["pool-sector-format"] = o.PoolSectorFormat
	}
	if !isNil(o.PoolSectorFormatNumeric) {
		toSerialize["pool-sector-format-numeric"] = o.PoolSectorFormatNumeric
	}
	if !isNil(o.PreferredOwner) {
		toSerialize["preferred-owner"] = o.PreferredOwner
	}
	if !isNil(o.PreferredOwnerNumeric) {
		toSerialize["preferred-owner-numeric"] = o.PreferredOwnerNumeric
	}
	if !isNil(o.ReadFlashCache) {
		toSerialize["read-flash-cache"] = o.ReadFlashCache
	}
	if !isNil(o.ReadFlashCacheNumeric) {
		toSerialize["read-flash-cache-numeric"] = o.ReadFlashCacheNumeric
	}
	if !isNil(o.Rebalance) {
		toSerialize["rebalance"] = o.Rebalance
	}
	if !isNil(o.RebalanceNumeric) {
		toSerialize["rebalance-numeric"] = o.RebalanceNumeric
	}
	if !isNil(o.ReservedSize) {
		toSerialize["reserved-size"] = o.ReservedSize
	}
	if !isNil(o.ReservedSizeNumeric) {
		toSerialize["reserved-size-numeric"] = o.ReservedSizeNumeric
	}
	if !isNil(o.ReservedUnallocSize) {
		toSerialize["reserved-unalloc-size"] = o.ReservedUnallocSize
	}
	if !isNil(o.ReservedUnallocSizeNumeric) {
		toSerialize["reserved-unalloc-size-numeric"] = o.ReservedUnallocSizeNumeric
	}
	if !isNil(o.SerialNumber) {
		toSerialize["serial-number"] = o.SerialNumber
	}
	if !isNil(o.SnapSize) {
		toSerialize["snap-size"] = o.SnapSize
	}
	if !isNil(o.SnapSizeNumeric) {
		toSerialize["snap-size-numeric"] = o.SnapSizeNumeric
	}
	if !isNil(o.StorageType) {
		toSerialize["storage-type"] = o.StorageType
	}
	if !isNil(o.StorageTypeNumeric) {
		toSerialize["storage-type-numeric"] = o.StorageTypeNumeric
	}
	if !isNil(o.TotalAvail) {
		toSerialize["total-avail"] = o.TotalAvail
	}
	if !isNil(o.TotalAvailNumeric) {
		toSerialize["total-avail-numeric"] = o.TotalAvailNumeric
	}
	if !isNil(o.TotalRfcSize) {
		toSerialize["total-rfc-size"] = o.TotalRfcSize
	}
	if !isNil(o.TotalRfcSizeNumeric) {
		toSerialize["total-rfc-size-numeric"] = o.TotalRfcSizeNumeric
	}
	if !isNil(o.TotalSize) {
		toSerialize["total-size"] = o.TotalSize
	}
	if !isNil(o.TotalSizeNumeric) {
		toSerialize["total-size-numeric"] = o.TotalSizeNumeric
	}
	if !isNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !isNil(o.UtilityRunning) {
		toSerialize["utility-running"] = o.UtilityRunning
	}
	if !isNil(o.UtilityRunningNumeric) {
		toSerialize["utility-running-numeric"] = o.UtilityRunningNumeric
	}
	if !isNil(o.Volumes) {
		toSerialize["volumes"] = o.Volumes
	}
	if !isNil(o.ZeroScan) {
		toSerialize["zero-scan"] = o.ZeroScan
	}
	if !isNil(o.ZeroScanNumeric) {
		toSerialize["zero-scan-numeric"] = o.ZeroScanNumeric
	}
	if !isNil(o.DiskGroups) {
		toSerialize["disk-groups"] = o.DiskGroups
	}
	if !isNil(o.Tiers) {
		toSerialize["tiers"] = o.Tiers
	}
	return json.Marshal(toSerialize)
}

type NullablePoolsResourceInner struct {
	value *PoolsResourceInner
	isSet bool
}

func (v NullablePoolsResourceInner) Get() *PoolsResourceInner {
	return v.value
}

func (v *NullablePoolsResourceInner) Set(val *PoolsResourceInner) {
	v.value = val
	v.isSet = true
}

func (v NullablePoolsResourceInner) IsSet() bool {
	return v.isSet
}

func (v *NullablePoolsResourceInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePoolsResourceInner(val *PoolsResourceInner) *NullablePoolsResourceInner {
	return &NullablePoolsResourceInner{value: val, isSet: true}
}

func (v NullablePoolsResourceInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePoolsResourceInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
