/*
Seagate Management Controller (MC) OpenAPI

This API allows users to interact through the MC API to provision and manage storage.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the HostGroupViewObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HostGroupViewObject{}

// HostGroupViewObject struct for HostGroupViewObject
type HostGroupViewObject struct {
	Status        []StatusResourceInner        `json:"status,omitempty"`
	HostGroupView []HostGroupViewResourceInner `json:"host-group-view,omitempty"`
}

// NewHostGroupViewObject instantiates a new HostGroupViewObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHostGroupViewObject() *HostGroupViewObject {
	this := HostGroupViewObject{}
	return &this
}

// NewHostGroupViewObjectWithDefaults instantiates a new HostGroupViewObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHostGroupViewObjectWithDefaults() *HostGroupViewObject {
	this := HostGroupViewObject{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *HostGroupViewObject) GetStatus() []StatusResourceInner {
	if o == nil || IsNil(o.Status) {
		var ret []StatusResourceInner
		return ret
	}
	return o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HostGroupViewObject) GetStatusOk() ([]StatusResourceInner, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *HostGroupViewObject) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given []StatusResourceInner and assigns it to the Status field.
func (o *HostGroupViewObject) SetStatus(v []StatusResourceInner) {
	o.Status = v
}

// GetHostGroupView returns the HostGroupView field value if set, zero value otherwise.
func (o *HostGroupViewObject) GetHostGroupView() []HostGroupViewResourceInner {
	if o == nil || IsNil(o.HostGroupView) {
		var ret []HostGroupViewResourceInner
		return ret
	}
	return o.HostGroupView
}

// GetHostGroupViewOk returns a tuple with the HostGroupView field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HostGroupViewObject) GetHostGroupViewOk() ([]HostGroupViewResourceInner, bool) {
	if o == nil || IsNil(o.HostGroupView) {
		return nil, false
	}
	return o.HostGroupView, true
}

// HasHostGroupView returns a boolean if a field has been set.
func (o *HostGroupViewObject) HasHostGroupView() bool {
	if o != nil && !IsNil(o.HostGroupView) {
		return true
	}

	return false
}

// SetHostGroupView gets a reference to the given []HostGroupViewResourceInner and assigns it to the HostGroupView field.
func (o *HostGroupViewObject) SetHostGroupView(v []HostGroupViewResourceInner) {
	o.HostGroupView = v
}

func (o HostGroupViewObject) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HostGroupViewObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.HostGroupView) {
		toSerialize["host-group-view"] = o.HostGroupView
	}
	return toSerialize, nil
}

type NullableHostGroupViewObject struct {
	value *HostGroupViewObject
	isSet bool
}

func (v NullableHostGroupViewObject) Get() *HostGroupViewObject {
	return v.value
}

func (v *NullableHostGroupViewObject) Set(val *HostGroupViewObject) {
	v.value = val
	v.isSet = true
}

func (v NullableHostGroupViewObject) IsSet() bool {
	return v.isSet
}

func (v *NullableHostGroupViewObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHostGroupViewObject(val *HostGroupViewObject) *NullableHostGroupViewObject {
	return &NullableHostGroupViewObject{value: val, isSet: true}
}

func (v NullableHostGroupViewObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHostGroupViewObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
