/*
Seagate Management Controller (MC) OpenAPI

This API allows users to interact through the MC API to provision and manage storage.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the IscsiPortResourceInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IscsiPortResourceInner{}

// IscsiPortResourceInner struct for IscsiPortResourceInner
type IscsiPortResourceInner struct {
	ObjectName    *string `json:"object-name,omitempty"`
	Meta          *string `json:"meta,omitempty"`
	DefaultRouter *string `json:"default-router,omitempty"`
	Gateway       *string `json:"gateway,omitempty"`
	IpAddress     *string `json:"ip-address,omitempty"`
	IpVersion     *string `json:"ip-version,omitempty"`
	// IPv6 Link-Local Address
	LinkLocalAddress *string `json:"link-local-address,omitempty"`
	// Primary MAC address for the port
	MacAddress *string `json:"mac-address,omitempty"`
	// Netmask of the iSCSI IP address for this port
	Netmask                      *string `json:"netmask,omitempty"`
	Sfp10GCompliance             *string `json:"sfp-10G-compliance,omitempty"`
	Sfp10GComplianceNumeric      *int64  `json:"sfp-10G-compliance-numeric,omitempty"`
	SfpCableLength               *int64  `json:"sfp-cable-length,omitempty"`
	SfpCableTechnology           *string `json:"sfp-cable-technology,omitempty"`
	SfpCableTechnologyNumeric    *int64  `json:"sfp-cable-technology-numeric,omitempty"`
	SfpEthernetCompliance        *string `json:"sfp-ethernet-compliance,omitempty"`
	SfpEthernetComplianceNumeric *int64  `json:"sfp-ethernet-compliance-numeric,omitempty"`
	SfpPartNumber                *string `json:"sfp-part-number,omitempty"`
	SfpPresent                   *string `json:"sfp-present,omitempty"`
	SfpPresentNumeric            *int64  `json:"sfp-present-numeric,omitempty"`
	SfpRevision                  *string `json:"sfp-revision,omitempty"`
	SfpStatus                    *string `json:"sfp-status,omitempty"`
	SfpStatusNumeric             *int64  `json:"sfp-status-numeric,omitempty"`
	SfpVendor                    *string `json:"sfp-vendor,omitempty"`
}

// NewIscsiPortResourceInner instantiates a new IscsiPortResourceInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIscsiPortResourceInner() *IscsiPortResourceInner {
	this := IscsiPortResourceInner{}
	return &this
}

// NewIscsiPortResourceInnerWithDefaults instantiates a new IscsiPortResourceInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIscsiPortResourceInnerWithDefaults() *IscsiPortResourceInner {
	this := IscsiPortResourceInner{}
	return &this
}

// GetObjectName returns the ObjectName field value if set, zero value otherwise.
func (o *IscsiPortResourceInner) GetObjectName() string {
	if o == nil || IsNil(o.ObjectName) {
		var ret string
		return ret
	}
	return *o.ObjectName
}

// GetObjectNameOk returns a tuple with the ObjectName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IscsiPortResourceInner) GetObjectNameOk() (*string, bool) {
	if o == nil || IsNil(o.ObjectName) {
		return nil, false
	}
	return o.ObjectName, true
}

// HasObjectName returns a boolean if a field has been set.
func (o *IscsiPortResourceInner) HasObjectName() bool {
	if o != nil && !IsNil(o.ObjectName) {
		return true
	}

	return false
}

// SetObjectName gets a reference to the given string and assigns it to the ObjectName field.
func (o *IscsiPortResourceInner) SetObjectName(v string) {
	o.ObjectName = &v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *IscsiPortResourceInner) GetMeta() string {
	if o == nil || IsNil(o.Meta) {
		var ret string
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IscsiPortResourceInner) GetMetaOk() (*string, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *IscsiPortResourceInner) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given string and assigns it to the Meta field.
func (o *IscsiPortResourceInner) SetMeta(v string) {
	o.Meta = &v
}

// GetDefaultRouter returns the DefaultRouter field value if set, zero value otherwise.
func (o *IscsiPortResourceInner) GetDefaultRouter() string {
	if o == nil || IsNil(o.DefaultRouter) {
		var ret string
		return ret
	}
	return *o.DefaultRouter
}

// GetDefaultRouterOk returns a tuple with the DefaultRouter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IscsiPortResourceInner) GetDefaultRouterOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultRouter) {
		return nil, false
	}
	return o.DefaultRouter, true
}

// HasDefaultRouter returns a boolean if a field has been set.
func (o *IscsiPortResourceInner) HasDefaultRouter() bool {
	if o != nil && !IsNil(o.DefaultRouter) {
		return true
	}

	return false
}

// SetDefaultRouter gets a reference to the given string and assigns it to the DefaultRouter field.
func (o *IscsiPortResourceInner) SetDefaultRouter(v string) {
	o.DefaultRouter = &v
}

// GetGateway returns the Gateway field value if set, zero value otherwise.
func (o *IscsiPortResourceInner) GetGateway() string {
	if o == nil || IsNil(o.Gateway) {
		var ret string
		return ret
	}
	return *o.Gateway
}

// GetGatewayOk returns a tuple with the Gateway field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IscsiPortResourceInner) GetGatewayOk() (*string, bool) {
	if o == nil || IsNil(o.Gateway) {
		return nil, false
	}
	return o.Gateway, true
}

// HasGateway returns a boolean if a field has been set.
func (o *IscsiPortResourceInner) HasGateway() bool {
	if o != nil && !IsNil(o.Gateway) {
		return true
	}

	return false
}

// SetGateway gets a reference to the given string and assigns it to the Gateway field.
func (o *IscsiPortResourceInner) SetGateway(v string) {
	o.Gateway = &v
}

// GetIpAddress returns the IpAddress field value if set, zero value otherwise.
func (o *IscsiPortResourceInner) GetIpAddress() string {
	if o == nil || IsNil(o.IpAddress) {
		var ret string
		return ret
	}
	return *o.IpAddress
}

// GetIpAddressOk returns a tuple with the IpAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IscsiPortResourceInner) GetIpAddressOk() (*string, bool) {
	if o == nil || IsNil(o.IpAddress) {
		return nil, false
	}
	return o.IpAddress, true
}

// HasIpAddress returns a boolean if a field has been set.
func (o *IscsiPortResourceInner) HasIpAddress() bool {
	if o != nil && !IsNil(o.IpAddress) {
		return true
	}

	return false
}

// SetIpAddress gets a reference to the given string and assigns it to the IpAddress field.
func (o *IscsiPortResourceInner) SetIpAddress(v string) {
	o.IpAddress = &v
}

// GetIpVersion returns the IpVersion field value if set, zero value otherwise.
func (o *IscsiPortResourceInner) GetIpVersion() string {
	if o == nil || IsNil(o.IpVersion) {
		var ret string
		return ret
	}
	return *o.IpVersion
}

// GetIpVersionOk returns a tuple with the IpVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IscsiPortResourceInner) GetIpVersionOk() (*string, bool) {
	if o == nil || IsNil(o.IpVersion) {
		return nil, false
	}
	return o.IpVersion, true
}

// HasIpVersion returns a boolean if a field has been set.
func (o *IscsiPortResourceInner) HasIpVersion() bool {
	if o != nil && !IsNil(o.IpVersion) {
		return true
	}

	return false
}

// SetIpVersion gets a reference to the given string and assigns it to the IpVersion field.
func (o *IscsiPortResourceInner) SetIpVersion(v string) {
	o.IpVersion = &v
}

// GetLinkLocalAddress returns the LinkLocalAddress field value if set, zero value otherwise.
func (o *IscsiPortResourceInner) GetLinkLocalAddress() string {
	if o == nil || IsNil(o.LinkLocalAddress) {
		var ret string
		return ret
	}
	return *o.LinkLocalAddress
}

// GetLinkLocalAddressOk returns a tuple with the LinkLocalAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IscsiPortResourceInner) GetLinkLocalAddressOk() (*string, bool) {
	if o == nil || IsNil(o.LinkLocalAddress) {
		return nil, false
	}
	return o.LinkLocalAddress, true
}

// HasLinkLocalAddress returns a boolean if a field has been set.
func (o *IscsiPortResourceInner) HasLinkLocalAddress() bool {
	if o != nil && !IsNil(o.LinkLocalAddress) {
		return true
	}

	return false
}

// SetLinkLocalAddress gets a reference to the given string and assigns it to the LinkLocalAddress field.
func (o *IscsiPortResourceInner) SetLinkLocalAddress(v string) {
	o.LinkLocalAddress = &v
}

// GetMacAddress returns the MacAddress field value if set, zero value otherwise.
func (o *IscsiPortResourceInner) GetMacAddress() string {
	if o == nil || IsNil(o.MacAddress) {
		var ret string
		return ret
	}
	return *o.MacAddress
}

// GetMacAddressOk returns a tuple with the MacAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IscsiPortResourceInner) GetMacAddressOk() (*string, bool) {
	if o == nil || IsNil(o.MacAddress) {
		return nil, false
	}
	return o.MacAddress, true
}

// HasMacAddress returns a boolean if a field has been set.
func (o *IscsiPortResourceInner) HasMacAddress() bool {
	if o != nil && !IsNil(o.MacAddress) {
		return true
	}

	return false
}

// SetMacAddress gets a reference to the given string and assigns it to the MacAddress field.
func (o *IscsiPortResourceInner) SetMacAddress(v string) {
	o.MacAddress = &v
}

// GetNetmask returns the Netmask field value if set, zero value otherwise.
func (o *IscsiPortResourceInner) GetNetmask() string {
	if o == nil || IsNil(o.Netmask) {
		var ret string
		return ret
	}
	return *o.Netmask
}

// GetNetmaskOk returns a tuple with the Netmask field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IscsiPortResourceInner) GetNetmaskOk() (*string, bool) {
	if o == nil || IsNil(o.Netmask) {
		return nil, false
	}
	return o.Netmask, true
}

// HasNetmask returns a boolean if a field has been set.
func (o *IscsiPortResourceInner) HasNetmask() bool {
	if o != nil && !IsNil(o.Netmask) {
		return true
	}

	return false
}

// SetNetmask gets a reference to the given string and assigns it to the Netmask field.
func (o *IscsiPortResourceInner) SetNetmask(v string) {
	o.Netmask = &v
}

// GetSfp10GCompliance returns the Sfp10GCompliance field value if set, zero value otherwise.
func (o *IscsiPortResourceInner) GetSfp10GCompliance() string {
	if o == nil || IsNil(o.Sfp10GCompliance) {
		var ret string
		return ret
	}
	return *o.Sfp10GCompliance
}

// GetSfp10GComplianceOk returns a tuple with the Sfp10GCompliance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IscsiPortResourceInner) GetSfp10GComplianceOk() (*string, bool) {
	if o == nil || IsNil(o.Sfp10GCompliance) {
		return nil, false
	}
	return o.Sfp10GCompliance, true
}

// HasSfp10GCompliance returns a boolean if a field has been set.
func (o *IscsiPortResourceInner) HasSfp10GCompliance() bool {
	if o != nil && !IsNil(o.Sfp10GCompliance) {
		return true
	}

	return false
}

// SetSfp10GCompliance gets a reference to the given string and assigns it to the Sfp10GCompliance field.
func (o *IscsiPortResourceInner) SetSfp10GCompliance(v string) {
	o.Sfp10GCompliance = &v
}

// GetSfp10GComplianceNumeric returns the Sfp10GComplianceNumeric field value if set, zero value otherwise.
func (o *IscsiPortResourceInner) GetSfp10GComplianceNumeric() int64 {
	if o == nil || IsNil(o.Sfp10GComplianceNumeric) {
		var ret int64
		return ret
	}
	return *o.Sfp10GComplianceNumeric
}

// GetSfp10GComplianceNumericOk returns a tuple with the Sfp10GComplianceNumeric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IscsiPortResourceInner) GetSfp10GComplianceNumericOk() (*int64, bool) {
	if o == nil || IsNil(o.Sfp10GComplianceNumeric) {
		return nil, false
	}
	return o.Sfp10GComplianceNumeric, true
}

// HasSfp10GComplianceNumeric returns a boolean if a field has been set.
func (o *IscsiPortResourceInner) HasSfp10GComplianceNumeric() bool {
	if o != nil && !IsNil(o.Sfp10GComplianceNumeric) {
		return true
	}

	return false
}

// SetSfp10GComplianceNumeric gets a reference to the given int64 and assigns it to the Sfp10GComplianceNumeric field.
func (o *IscsiPortResourceInner) SetSfp10GComplianceNumeric(v int64) {
	o.Sfp10GComplianceNumeric = &v
}

// GetSfpCableLength returns the SfpCableLength field value if set, zero value otherwise.
func (o *IscsiPortResourceInner) GetSfpCableLength() int64 {
	if o == nil || IsNil(o.SfpCableLength) {
		var ret int64
		return ret
	}
	return *o.SfpCableLength
}

// GetSfpCableLengthOk returns a tuple with the SfpCableLength field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IscsiPortResourceInner) GetSfpCableLengthOk() (*int64, bool) {
	if o == nil || IsNil(o.SfpCableLength) {
		return nil, false
	}
	return o.SfpCableLength, true
}

// HasSfpCableLength returns a boolean if a field has been set.
func (o *IscsiPortResourceInner) HasSfpCableLength() bool {
	if o != nil && !IsNil(o.SfpCableLength) {
		return true
	}

	return false
}

// SetSfpCableLength gets a reference to the given int64 and assigns it to the SfpCableLength field.
func (o *IscsiPortResourceInner) SetSfpCableLength(v int64) {
	o.SfpCableLength = &v
}

// GetSfpCableTechnology returns the SfpCableTechnology field value if set, zero value otherwise.
func (o *IscsiPortResourceInner) GetSfpCableTechnology() string {
	if o == nil || IsNil(o.SfpCableTechnology) {
		var ret string
		return ret
	}
	return *o.SfpCableTechnology
}

// GetSfpCableTechnologyOk returns a tuple with the SfpCableTechnology field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IscsiPortResourceInner) GetSfpCableTechnologyOk() (*string, bool) {
	if o == nil || IsNil(o.SfpCableTechnology) {
		return nil, false
	}
	return o.SfpCableTechnology, true
}

// HasSfpCableTechnology returns a boolean if a field has been set.
func (o *IscsiPortResourceInner) HasSfpCableTechnology() bool {
	if o != nil && !IsNil(o.SfpCableTechnology) {
		return true
	}

	return false
}

// SetSfpCableTechnology gets a reference to the given string and assigns it to the SfpCableTechnology field.
func (o *IscsiPortResourceInner) SetSfpCableTechnology(v string) {
	o.SfpCableTechnology = &v
}

// GetSfpCableTechnologyNumeric returns the SfpCableTechnologyNumeric field value if set, zero value otherwise.
func (o *IscsiPortResourceInner) GetSfpCableTechnologyNumeric() int64 {
	if o == nil || IsNil(o.SfpCableTechnologyNumeric) {
		var ret int64
		return ret
	}
	return *o.SfpCableTechnologyNumeric
}

// GetSfpCableTechnologyNumericOk returns a tuple with the SfpCableTechnologyNumeric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IscsiPortResourceInner) GetSfpCableTechnologyNumericOk() (*int64, bool) {
	if o == nil || IsNil(o.SfpCableTechnologyNumeric) {
		return nil, false
	}
	return o.SfpCableTechnologyNumeric, true
}

// HasSfpCableTechnologyNumeric returns a boolean if a field has been set.
func (o *IscsiPortResourceInner) HasSfpCableTechnologyNumeric() bool {
	if o != nil && !IsNil(o.SfpCableTechnologyNumeric) {
		return true
	}

	return false
}

// SetSfpCableTechnologyNumeric gets a reference to the given int64 and assigns it to the SfpCableTechnologyNumeric field.
func (o *IscsiPortResourceInner) SetSfpCableTechnologyNumeric(v int64) {
	o.SfpCableTechnologyNumeric = &v
}

// GetSfpEthernetCompliance returns the SfpEthernetCompliance field value if set, zero value otherwise.
func (o *IscsiPortResourceInner) GetSfpEthernetCompliance() string {
	if o == nil || IsNil(o.SfpEthernetCompliance) {
		var ret string
		return ret
	}
	return *o.SfpEthernetCompliance
}

// GetSfpEthernetComplianceOk returns a tuple with the SfpEthernetCompliance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IscsiPortResourceInner) GetSfpEthernetComplianceOk() (*string, bool) {
	if o == nil || IsNil(o.SfpEthernetCompliance) {
		return nil, false
	}
	return o.SfpEthernetCompliance, true
}

// HasSfpEthernetCompliance returns a boolean if a field has been set.
func (o *IscsiPortResourceInner) HasSfpEthernetCompliance() bool {
	if o != nil && !IsNil(o.SfpEthernetCompliance) {
		return true
	}

	return false
}

// SetSfpEthernetCompliance gets a reference to the given string and assigns it to the SfpEthernetCompliance field.
func (o *IscsiPortResourceInner) SetSfpEthernetCompliance(v string) {
	o.SfpEthernetCompliance = &v
}

// GetSfpEthernetComplianceNumeric returns the SfpEthernetComplianceNumeric field value if set, zero value otherwise.
func (o *IscsiPortResourceInner) GetSfpEthernetComplianceNumeric() int64 {
	if o == nil || IsNil(o.SfpEthernetComplianceNumeric) {
		var ret int64
		return ret
	}
	return *o.SfpEthernetComplianceNumeric
}

// GetSfpEthernetComplianceNumericOk returns a tuple with the SfpEthernetComplianceNumeric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IscsiPortResourceInner) GetSfpEthernetComplianceNumericOk() (*int64, bool) {
	if o == nil || IsNil(o.SfpEthernetComplianceNumeric) {
		return nil, false
	}
	return o.SfpEthernetComplianceNumeric, true
}

// HasSfpEthernetComplianceNumeric returns a boolean if a field has been set.
func (o *IscsiPortResourceInner) HasSfpEthernetComplianceNumeric() bool {
	if o != nil && !IsNil(o.SfpEthernetComplianceNumeric) {
		return true
	}

	return false
}

// SetSfpEthernetComplianceNumeric gets a reference to the given int64 and assigns it to the SfpEthernetComplianceNumeric field.
func (o *IscsiPortResourceInner) SetSfpEthernetComplianceNumeric(v int64) {
	o.SfpEthernetComplianceNumeric = &v
}

// GetSfpPartNumber returns the SfpPartNumber field value if set, zero value otherwise.
func (o *IscsiPortResourceInner) GetSfpPartNumber() string {
	if o == nil || IsNil(o.SfpPartNumber) {
		var ret string
		return ret
	}
	return *o.SfpPartNumber
}

// GetSfpPartNumberOk returns a tuple with the SfpPartNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IscsiPortResourceInner) GetSfpPartNumberOk() (*string, bool) {
	if o == nil || IsNil(o.SfpPartNumber) {
		return nil, false
	}
	return o.SfpPartNumber, true
}

// HasSfpPartNumber returns a boolean if a field has been set.
func (o *IscsiPortResourceInner) HasSfpPartNumber() bool {
	if o != nil && !IsNil(o.SfpPartNumber) {
		return true
	}

	return false
}

// SetSfpPartNumber gets a reference to the given string and assigns it to the SfpPartNumber field.
func (o *IscsiPortResourceInner) SetSfpPartNumber(v string) {
	o.SfpPartNumber = &v
}

// GetSfpPresent returns the SfpPresent field value if set, zero value otherwise.
func (o *IscsiPortResourceInner) GetSfpPresent() string {
	if o == nil || IsNil(o.SfpPresent) {
		var ret string
		return ret
	}
	return *o.SfpPresent
}

// GetSfpPresentOk returns a tuple with the SfpPresent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IscsiPortResourceInner) GetSfpPresentOk() (*string, bool) {
	if o == nil || IsNil(o.SfpPresent) {
		return nil, false
	}
	return o.SfpPresent, true
}

// HasSfpPresent returns a boolean if a field has been set.
func (o *IscsiPortResourceInner) HasSfpPresent() bool {
	if o != nil && !IsNil(o.SfpPresent) {
		return true
	}

	return false
}

// SetSfpPresent gets a reference to the given string and assigns it to the SfpPresent field.
func (o *IscsiPortResourceInner) SetSfpPresent(v string) {
	o.SfpPresent = &v
}

// GetSfpPresentNumeric returns the SfpPresentNumeric field value if set, zero value otherwise.
func (o *IscsiPortResourceInner) GetSfpPresentNumeric() int64 {
	if o == nil || IsNil(o.SfpPresentNumeric) {
		var ret int64
		return ret
	}
	return *o.SfpPresentNumeric
}

// GetSfpPresentNumericOk returns a tuple with the SfpPresentNumeric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IscsiPortResourceInner) GetSfpPresentNumericOk() (*int64, bool) {
	if o == nil || IsNil(o.SfpPresentNumeric) {
		return nil, false
	}
	return o.SfpPresentNumeric, true
}

// HasSfpPresentNumeric returns a boolean if a field has been set.
func (o *IscsiPortResourceInner) HasSfpPresentNumeric() bool {
	if o != nil && !IsNil(o.SfpPresentNumeric) {
		return true
	}

	return false
}

// SetSfpPresentNumeric gets a reference to the given int64 and assigns it to the SfpPresentNumeric field.
func (o *IscsiPortResourceInner) SetSfpPresentNumeric(v int64) {
	o.SfpPresentNumeric = &v
}

// GetSfpRevision returns the SfpRevision field value if set, zero value otherwise.
func (o *IscsiPortResourceInner) GetSfpRevision() string {
	if o == nil || IsNil(o.SfpRevision) {
		var ret string
		return ret
	}
	return *o.SfpRevision
}

// GetSfpRevisionOk returns a tuple with the SfpRevision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IscsiPortResourceInner) GetSfpRevisionOk() (*string, bool) {
	if o == nil || IsNil(o.SfpRevision) {
		return nil, false
	}
	return o.SfpRevision, true
}

// HasSfpRevision returns a boolean if a field has been set.
func (o *IscsiPortResourceInner) HasSfpRevision() bool {
	if o != nil && !IsNil(o.SfpRevision) {
		return true
	}

	return false
}

// SetSfpRevision gets a reference to the given string and assigns it to the SfpRevision field.
func (o *IscsiPortResourceInner) SetSfpRevision(v string) {
	o.SfpRevision = &v
}

// GetSfpStatus returns the SfpStatus field value if set, zero value otherwise.
func (o *IscsiPortResourceInner) GetSfpStatus() string {
	if o == nil || IsNil(o.SfpStatus) {
		var ret string
		return ret
	}
	return *o.SfpStatus
}

// GetSfpStatusOk returns a tuple with the SfpStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IscsiPortResourceInner) GetSfpStatusOk() (*string, bool) {
	if o == nil || IsNil(o.SfpStatus) {
		return nil, false
	}
	return o.SfpStatus, true
}

// HasSfpStatus returns a boolean if a field has been set.
func (o *IscsiPortResourceInner) HasSfpStatus() bool {
	if o != nil && !IsNil(o.SfpStatus) {
		return true
	}

	return false
}

// SetSfpStatus gets a reference to the given string and assigns it to the SfpStatus field.
func (o *IscsiPortResourceInner) SetSfpStatus(v string) {
	o.SfpStatus = &v
}

// GetSfpStatusNumeric returns the SfpStatusNumeric field value if set, zero value otherwise.
func (o *IscsiPortResourceInner) GetSfpStatusNumeric() int64 {
	if o == nil || IsNil(o.SfpStatusNumeric) {
		var ret int64
		return ret
	}
	return *o.SfpStatusNumeric
}

// GetSfpStatusNumericOk returns a tuple with the SfpStatusNumeric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IscsiPortResourceInner) GetSfpStatusNumericOk() (*int64, bool) {
	if o == nil || IsNil(o.SfpStatusNumeric) {
		return nil, false
	}
	return o.SfpStatusNumeric, true
}

// HasSfpStatusNumeric returns a boolean if a field has been set.
func (o *IscsiPortResourceInner) HasSfpStatusNumeric() bool {
	if o != nil && !IsNil(o.SfpStatusNumeric) {
		return true
	}

	return false
}

// SetSfpStatusNumeric gets a reference to the given int64 and assigns it to the SfpStatusNumeric field.
func (o *IscsiPortResourceInner) SetSfpStatusNumeric(v int64) {
	o.SfpStatusNumeric = &v
}

// GetSfpVendor returns the SfpVendor field value if set, zero value otherwise.
func (o *IscsiPortResourceInner) GetSfpVendor() string {
	if o == nil || IsNil(o.SfpVendor) {
		var ret string
		return ret
	}
	return *o.SfpVendor
}

// GetSfpVendorOk returns a tuple with the SfpVendor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IscsiPortResourceInner) GetSfpVendorOk() (*string, bool) {
	if o == nil || IsNil(o.SfpVendor) {
		return nil, false
	}
	return o.SfpVendor, true
}

// HasSfpVendor returns a boolean if a field has been set.
func (o *IscsiPortResourceInner) HasSfpVendor() bool {
	if o != nil && !IsNil(o.SfpVendor) {
		return true
	}

	return false
}

// SetSfpVendor gets a reference to the given string and assigns it to the SfpVendor field.
func (o *IscsiPortResourceInner) SetSfpVendor(v string) {
	o.SfpVendor = &v
}

func (o IscsiPortResourceInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IscsiPortResourceInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ObjectName) {
		toSerialize["object-name"] = o.ObjectName
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	if !IsNil(o.DefaultRouter) {
		toSerialize["default-router"] = o.DefaultRouter
	}
	if !IsNil(o.Gateway) {
		toSerialize["gateway"] = o.Gateway
	}
	if !IsNil(o.IpAddress) {
		toSerialize["ip-address"] = o.IpAddress
	}
	if !IsNil(o.IpVersion) {
		toSerialize["ip-version"] = o.IpVersion
	}
	if !IsNil(o.LinkLocalAddress) {
		toSerialize["link-local-address"] = o.LinkLocalAddress
	}
	if !IsNil(o.MacAddress) {
		toSerialize["mac-address"] = o.MacAddress
	}
	if !IsNil(o.Netmask) {
		toSerialize["netmask"] = o.Netmask
	}
	if !IsNil(o.Sfp10GCompliance) {
		toSerialize["sfp-10G-compliance"] = o.Sfp10GCompliance
	}
	if !IsNil(o.Sfp10GComplianceNumeric) {
		toSerialize["sfp-10G-compliance-numeric"] = o.Sfp10GComplianceNumeric
	}
	if !IsNil(o.SfpCableLength) {
		toSerialize["sfp-cable-length"] = o.SfpCableLength
	}
	if !IsNil(o.SfpCableTechnology) {
		toSerialize["sfp-cable-technology"] = o.SfpCableTechnology
	}
	if !IsNil(o.SfpCableTechnologyNumeric) {
		toSerialize["sfp-cable-technology-numeric"] = o.SfpCableTechnologyNumeric
	}
	if !IsNil(o.SfpEthernetCompliance) {
		toSerialize["sfp-ethernet-compliance"] = o.SfpEthernetCompliance
	}
	if !IsNil(o.SfpEthernetComplianceNumeric) {
		toSerialize["sfp-ethernet-compliance-numeric"] = o.SfpEthernetComplianceNumeric
	}
	if !IsNil(o.SfpPartNumber) {
		toSerialize["sfp-part-number"] = o.SfpPartNumber
	}
	if !IsNil(o.SfpPresent) {
		toSerialize["sfp-present"] = o.SfpPresent
	}
	if !IsNil(o.SfpPresentNumeric) {
		toSerialize["sfp-present-numeric"] = o.SfpPresentNumeric
	}
	if !IsNil(o.SfpRevision) {
		toSerialize["sfp-revision"] = o.SfpRevision
	}
	if !IsNil(o.SfpStatus) {
		toSerialize["sfp-status"] = o.SfpStatus
	}
	if !IsNil(o.SfpStatusNumeric) {
		toSerialize["sfp-status-numeric"] = o.SfpStatusNumeric
	}
	if !IsNil(o.SfpVendor) {
		toSerialize["sfp-vendor"] = o.SfpVendor
	}
	return toSerialize, nil
}

type NullableIscsiPortResourceInner struct {
	value *IscsiPortResourceInner
	isSet bool
}

func (v NullableIscsiPortResourceInner) Get() *IscsiPortResourceInner {
	return v.value
}

func (v *NullableIscsiPortResourceInner) Set(val *IscsiPortResourceInner) {
	v.value = val
	v.isSet = true
}

func (v NullableIscsiPortResourceInner) IsSet() bool {
	return v.isSet
}

func (v *NullableIscsiPortResourceInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIscsiPortResourceInner(val *IscsiPortResourceInner) *NullableIscsiPortResourceInner {
	return &NullableIscsiPortResourceInner{value: val, isSet: true}
}

func (v NullableIscsiPortResourceInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIscsiPortResourceInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
