name: Release

on:
  push:
    branches:
      - main

jobs:

  release:
    name: Update Release
    runs-on: ubuntu-latest

    steps:
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: ridedott/release-me-action@master
        with:
          disable-changelog: true

      - name: Output
          if: steps.build_package.outputs.released == 'true'
          run: echo "released version: ${{ steps.build_package.outputs.version }}, type: ${{ steps.build_package.outputs.level }}"
